### ISSUE TITLE
GDAL warper access?

### ISSUE THREAD

**Issue by weagle08** [naturalatlas/node-gdal#100]
Noob question maybe, but how do I access the gdal_warper.cpp class? I do not see a way to get to it in the documentation. It is one of the final touches I need for my nodejs wms server. :)
Hope to make it a git hub project if it works well enough for me to not be embarrassed... :)

**Comment by brandonreavis** [comment]
Hey! Have you looked into the [`gdal.reprojectImage()`](http://naturalatlas.github.io/node-gdal/classes/gdal.html#method-reprojectImage) and [ `gdal.suggestedWarpOutput()`](http://naturalatlas.github.io/node-gdal/classes/gdal.html#method-suggestedWarpOutput) methods? Currently they are the only methods from gdal_warper.cpp that are exposed, but they can do a lot of different things. Someday the various other methods may be added to node-gdal for finer control of warping, but my guess is that will be the distant future.

**Comment by weagle08** [comment]
Nope, and now that you point them out I see them in the documentation on the gdal object. thanks a lot! the gdal.reprojectImage should be all I need for a wms server. Thanks for this library, it has been great!

**Comment by weagle08** [comment]
Just want to point out I was issue 100!!! :)

**Comment by weagle08** [comment]
Going to reopen this issue real quick...  My use case:
1) I have initial in memory image (srs: EPSG:3857) of wxh
2) I would like to "reproject" the image to the same SRS, but just to a w'xh' tile (usually this will be 256x256) I don't see an option on the reprojectImage call to pass in a desired width and height.

Could you suggest a best approach to this? If this capability is in the warper I could probably expose it with a little direction. Would be glad to help.

Also, does GDAL already have a way to take select parts from multiple images and pull together into single image, not necessarily including the source images in their entirety? I just would like optimal performance and my math/loops may be slower than something gdal has.

**Comment by weagle08** [comment]
I've found that the gdalbuildvrt in combination with the gdalwarp apps will give me exactly what I want... now just to wrap them for use in javascript.

**Comment by AlokBansal8** [comment]
@weagle08 were you able to complete your project and open-source it?
