### ISSUE TITLE
Bundle GDAL 2.0.0

### ISSUE THREAD

**Issue by brianreavis** [naturalatlas/node-gdal#110]
Now that it's stable, we should go for it: http://lists.osgeo.org/pipermail/gdal-dev/2015-June/042081.html

**Comment by springmeyer** [comment]
:+1:

**Comment by brianreavis** [comment]
All built and ready (0.6.0): https://github.com/naturalatlas/node-gdal/releases/tag/v0.6.0

**Comment by springmeyer** [comment]
\o/ thank you! Also node-mapnik > 3.4.0 will also start using GDAL 2.0 per https://github.com/mapnik/node-mapnik/blob/master/CHANGELOG.md#future
