### ISSUE TITLE
Unable to get the value of an integer field

### ISSUE THREAD

**Issue by jdesboeufs** [naturalatlas/node-gdal#112]
Hi,

I noticed `node-gdal` seems to be unable to `get` the value of an integer field, and throw this exception:
```
Error: Unsupported field type
```

I tried to investigate but I'm definitely not able to write C++ stuff.
So I wrote a test in PR #111.

Things work internally in GDAL, since I have been able to create the sample in the PR with `node-gdal`, adding one feature to a new dataset/layer. The integer field still being readable by `ogrinfo` tool.

Any idea?

Thank you!

**Comment by jdesboeufs** [comment]
According to PR #111 it is related to GDAL 2.0!

**Comment by brandonreavis** [comment]
Thanks for the test case! The problem is that that field used 64 bit integers and we didn't handle those yet, but we'll push out a new release with that fix as soon as it builds.

**Comment by jdesboeufs** [comment]
Cool!
Maybe you should add `OFTInteger64List` too, so the binding would be [100% compliant](http://www.gdal.org/ogr__core_8h.html#a787194bea637faf12d61643124a7c9fc).

I'm working on a French government infrastructure dedicated to import thousands of legacy datasets :D
(particularly MapInfo TABs and Shapefiles)
You will hate me :)

**Comment by brandonreavis** [comment]
Haha oh boy. Yeah I can try to do that... I'm pretty sure the integer / string list fields as they are now won't work either. Is there any chance you can provide some shapefiles / tests that use list fields? I have never run across one before haha.

**Comment by jdesboeufs** [comment]
I don't know if we have datasets with list fields.
Probably not ;)

But OK to provide tests if I find that.

**Comment by jdesboeufs** [comment]
Your last commit breaks the test.
I've rebased the PR branch.

**Comment by jdesboeufs** [comment]
I fixed the issue in my PR branch.
Travis CI builds are passing!

**Comment by jdesboeufs** [comment]
Fixed with #111
