### ISSUE TITLE
Shapefile integer datatype reported as null

### ISSUE THREAD

**Issue by infitude** [naturalatlas/node-gdal#116]
I've hit an issue with shapefile integer datatypes recently.  Not sure if this related to recent commits but here is a test that can be added to open_shp.test.js to reproduce;

			describe('field properties', function() {
				var integerDs = gdal.open(path.join(__dirname, "data/shp/sample_int64.shp"));
				var integerLayer = integerDs.layers.get(0);

				it('should evaluate datatypes', function() {
					assert.equal(integerLayer.fields.get(0).type, 'string');
					assert.equal(integerLayer.fields.get(3).type, 'number');
					assert.equal(integerLayer.fields.get(5).type, 'real');
					assert.equal(integerLayer.fields.get(10).type, 'date');
				})
			});

  506 passing (4s)
  8 pending
  1 failing

  1) Open ESRI Shapefile layer field properties should evaluate datatypes:
     AssertionError: expected null to equal 'number'
      at Context.<anonymous> (test/open_shp.test.js:72:13)

**Comment by brianreavis** [comment]
@infitude Thanks for the good test case! Turns out that was something overlooked in the 2.0 upgrade. As soon as the test build completes I'll push out a new version with this fix in place.
