### ISSUE TITLE
Bump node-pre-gyp

### ISSUE THREAD

**Issue by BergWerkGIS** [naturalatlas/node-gdal#118]
Could we bump `node-pre-gyp` to `0.6.9`?
We are preparing a new Mapbox Studio release and need all dependencies to reference the same node-pre-gyp version.

**Comment by springmeyer** [comment]
:+1: @BergWerkGIS - go ahead and commit to master bumping to latest. No harm in using the latest node-pre-gyp.

**Comment by BergWerkGIS** [comment]
@brandonreavis @brianreavis 

Ok to merge https://github.com/naturalatlas/node-gdal/pull/117/files ?

That way we get automatic publish for Visual Studio 2015 binaries via AppVeyor and don't have to do it manually.

**Comment by brianreavis** [comment]
@BergWerkGIS Looks good to me – go for it. In the process can you add back in the line that @springmeyer mentioned? It fixes a strange Windows/mocha bug:
```
npm install https://github.com/naturalatlas/mocha/archive/fix/333.tar.gz
```

**Comment by BergWerkGIS** [comment]
Still holding on a `npm publish`, AppVeyor builds are constantly failing, either because of timeouts with nodejs.org or when pushing binaries to S3.
Kicked off another build
https://ci.appveyor.com/project/brianreavis/node-gdal/build/534
If that doesn't succeed, I'm going to do it manually tomorrow.

**Comment by BergWerkGIS** [comment]
I finally made AppVeyor work as expected and the binaries for 0.7.1 are published.
https://ci.appveyor.com/project/brianreavis/node-gdal/build/543

Could one of you please `npm publish` as I don't have the permissions to do so?

**Comment by springmeyer** [comment]
@BergWerkGIS - just added you. But I realize we don't have a contributing doc that spells out steps leading up to `npm publish`. The two key things are to make sure `npm ls` works and make sure you don't have any cruft or unversioned files in your local checkout. I usually run `npm publish` from a fresh clone for this reason (after running `npm install` to make sure the bundled dep of node-pre-gyp is present).

**Comment by springmeyer** [comment]
@brianreavis - are you okay with @BergWerkGIS doing a publish? If so could you write up a quick doc on the steps you take before releasing?

**Comment by brianreavis** [comment]
@springmeyer Yeah, of course. I just run:
```sh
make release version=0.7.2 # or whatever
```
Although I suppose that won't work on Windows, and that also doesn't include your steps. It just runs the tests to make sure they pass

**Comment by BergWerkGIS** [comment]
Publish [was successful](https://www.npmjs.com/package/gdal), but the `post-publish` step failed.

Is this a problem? Docs haven't changed.

**Comment by brianreavis** [comment]
> `post-publish` step failed

Can you elaborate?

**Comment by BergWerkGIS** [comment]
`make release` doesn't work on Windows, so I did a fresh clone as suggested by @springmeyer before publishing, to make sure no unnecessary file get into the package.
That way, `yuidoc` wasn't installed and post-publish failed.
