### ISSUE TITLE
PGDump or PostgreSQL Drive support PG_USE_COPY

### ISSUE THREAD

**Issue by TimJMartin** [naturalatlas/node-gdal#124]
Not an issue but a question:

Looking through both the PGDump and PostgreSQL driver code I cannot see an option for
PG_USE_COPY. Is this possible?

I am currently using  
<code>
var options = ["PG_USE_COPY=YES"]
var outputName = "C:/temp/" + layer.name + ".sql
var ds = gdal.open(outputName, 'w', 'PGDump');
var outLayer = ds.layers.create(layer.name, srs, layer.geomType, options);
</code>

Which states PG_USE_COPY is not supported

Is there an alternative way to set it

Many thanks

**Comment by brandonreavis** [comment]
According to the [PGDump driver documentation](http://www.gdal.org/drv_pgdump.html) `PG_USE_COPY` should be set as an environment variable and not a creation option. This can be done with: 
```
gdal.config.set('PG_USE_COPY', 'YES');
```
Hopefully this helps!

**Comment by TimJMartin** [comment]
Worked perfectly thanks very much @brandonreavis
