### ISSUE TITLE
Include in Electron app

### ISSUE THREAD

**Issue by TimJMartin** [naturalatlas/node-gdal#127]
After @BergWerkGIS got /vsigzip working (https://github.com/naturalatlas/node-gdal/issues/125) I am now trying to bundle into a standalone app using Electron.

I initially receive:
```
Error: Module did not self register
```
Which seems to be caused by trying to use Native Modules (http://electron.atom.io/docs/v0.27.0/tutorial/using-native-node-modules/)

So I have subsequently installed Visual Studio Express 2013 and the SDK  and have tried the "Easy Way" by using:

```
npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild
```

This fails with the following error log:

```
2758 info install gdal@0.7.1
2759 verbose unsafe-perm in lifecycle true
2760 info gdal@0.7.1 Failed to exec install script
2761 verbose stack Error: gdal@0.7.1 install: `node-pre-gyp install --fallback-to-build`
2761 verbose stack Exit status 1
2761 verbose stack     at EventEmitter.<anonymous> (C:\Projects\Electron\GDAL_GUI\node_modules\electron-rebuild\node_modules\npm\lib\utils\lifecycle.js:214:16)
2761 verbose stack     at EventEmitter.emit (events.js:110:17)
2761 verbose stack     at ChildProcess.<anonymous> (C:\Projects\Electron\GDAL_GUI\node_modules\electron-rebuild\node_modules\npm\lib\utils\spawn.js:24:14)
2761 verbose stack     at ChildProcess.emit (events.js:110:17)
2761 verbose stack     at maybeClose (child_process.js:1015:16)
2761 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
2762 verbose pkgid gdal@0.7.1
2763 verbose cwd C:\Projects\Electron\GDAL_GUI\node_modules
2764 error Windows_NT 6.1.7601
2765 error argv "node" "C:\\Projects\\Electron\\GDAL_GUI\\node_modules\\electron-rebuild\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=0.33.7" "--arch=x64"
2766 error node v0.12.7
2767 error npm  v2.14.8
2768 error code ELIFECYCLE
2769 error gdal@0.7.1 install: `node-pre-gyp install --fallback-to-build`
2769 error Exit status 1
2770 error Failed at the gdal@0.7.1 install script 'node-pre-gyp install --fallback-to-build'.
2770 error This is most likely a problem with the gdal package,
2770 error not with npm itself.
2770 error Tell the author that this fails on your system:
2770 error     node-pre-gyp install --fallback-to-build
2770 error You can get their info via:
2770 error     npm owner ls gdal
2770 error There is likely additional logging output above.
2771 verbose exit [ 1, true ]
```
But not sure what this needs me to do, any ideas how I can get this to work?

**Comment by TimJMartin** [comment]
I have now tried the same thing on my MBP and I get a variety of errors depending on the method I pick to try and rebuild GDAL to an electron module.

If I simple install GDAL using

npm install gdal

And try and run the app I get the following error from electron:

Uncaught Exception:
Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/timmartin/Documents/Projects/GDAL_GUI/node_modules/gdal/lib/gdal.js:7:29)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

So if I follow the guide on the Electron website and try and use electron rebuild I run into the problem found here:

https://github.com/electronjs/electron-rebuild/issues/25

Unknown Runtime: 'electron'

Which there does not seem to be a solution to??!

So if I follow the guide to use NPM method I get them same error of Module Mismatch

Finally if i use the node-gyp method I get the following error:

Undefined variable module_name in binding.gyp

Which seems to be caused by node-pre-gyp being bundled with GDAL and it seems you should use node-pre-gyp rebuild.

So I can the following:

node-pre-gyp rebuild --runtime=electron --target=0.33.7

Which I got really excited about because it ran for at least 5 minutes doing "things" and then unfortunately that failed to:

9 errors generated.
make: *** [Release/obj.target/gdal/src/utils/fast_buffer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--runtime=electron" "--target=0.33.7" "--module=/Users/timmartin/Documents/Projects/GDAL_GUI/node_modules/gdal/lib/binding/gdal.node" "--module_name=gdal" "--module_path=/Users/timmartin/Documents/Projects/GDAL_GUI/node_modules/gdal/lib/binding"
gyp ERR! cwd /Users/timmartin/Documents/Projects/GDAL_GUI/node_modules/gdal
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --runtime=electron --target=0.33.7 --module=/Users/timmartin/Documents/Projects/GDAL_GUI/node_modules/gdal/lib/binding/gdal.node --module_name=gdal --module_path=/Users/timmartin/Documents/Projects/GDAL_GUI/node_modules/gdal/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 13.4.0
node-pre-gyp ERR! command "node" "/usr/local/bin/node-pre-gyp" "rebuild" "--runtime=electron" "--target=0.33.7"
node-pre-gyp ERR! cwd /Users/timmartin/Documents/Projects/GDAL_GUI/node_modules/gdal
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.12
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --runtime=electron --target=0.33.7 --module=/Users/timmartin/Documents/Projects/GDAL_GUI/node_modules/gdal/lib/binding/gdal.node --module_name=gdal --module_path=/Users/timmartin/Documents/Projects/GDAL_GUI/node_modules/gdal/lib/binding' (1)


Maybe this is not a GDAL problem?

Sorry this is all a bit new to me but have now run out of ideas so any help would be awesome

thanks

**Comment by brianreavis** [comment]
This hinges on https://github.com/naturalatlas/node-gdal/issues/119, which I think @brandonreavis is going to try to get wrapped up today. Electron uses io.js 3.1.0 [source](http://electron.atom.io/docs/v0.33.0/tutorial/using-native-node-modules/), which requires the NAN upgrade to be in place.

**Comment by TimJMartin** [comment]
hey @brianreavis 

Yes I did wonder whether all the different versions was going to be the real issue.

if @brandonreavis manages to then I am more than happy to test. 

cheers

Tim

**Comment by brianreavis** [comment]
@TimJMartin Mind giving `0.7.2` a shot?

**Comment by TimJMartin** [comment]
@brianreavis just done a fresh install using

npm install gdal

and it is v0.7.2 and it installs successfully.

I now receieve an error saying:

Error: %1 is not a valid Win32 application and points to the gdal.node file in binding.

Should I change my Node version which is currently v0.12.7 x64?

**Comment by BergWerkGIS** [comment]
@TimJMartin We are still working on supporting `node-gdal`on Windows with `node>0.12.7`.
At the moment these versions have been removed from the build process:
https://github.com/naturalatlas/node-gdal/commit/f556d143c95df9c8011688857433e70a401300fc
I'm at it and hope to provide something useful within some days.

**Comment by TimJMartin** [comment]
@BergWerkGIS that sounds great

will test gdal 0.7.2 with electron on my MBP later on today and feedback

**Comment by BergWerkGIS** [comment]
@TimJMartin I've never done anything with electron, so I would be great, if you could either describe in a bit more detail, what you are doing exactly or even provide a skeleton of the app you are trying to build (ping me for private contact info, if needed).

Here's what I did so far:
* Windows builds of `node-gdal` are now working with `node@3.3.1` and `node@4.2.1` (https://ci.appveyor.com/project/brianreavis/node-gdal/build/581), but no binaries published yet. Lives in https://github.com/naturalatlas/node-gdal/tree/win-node-4.2.1 branch ATM.
* with `node@4.2.1`: `npm install --save-dev electron-rebuild`
  * installed a lot of deps
  * ended with
```
npm WARN ENOENT ENOENT: no such file or directory, open 'package.json'
```
* created a `package.json` with 
```
  "dependencies": {
    "gdal": "naturalatlas/node-gdal#win-node-4.2.1"
  },
```
* `npm install --save-dev electron-rebuild` ran through without error
* `node_modules\.bin\electron-rebuild.cmd` errored with
```
Unable to find electron-prebuilt's version number, either install it or specify an explicit version
```
* following the advise in http://stackoverflow.com/a/30113644 I did `npm install electron-prebuilt`, which ran through without error
* then `node_modules\.bin\electron-rebuild.cmd` complained to not be able to delete `node_modules\nslog\build\Release\nslog.node`
* deleted it manually
* then `node_modules\.bin\electron-rebuild.cmd` ran through without error

What's next?

**Comment by BergWerkGIS** [comment]
Works! Used `node@4.2.1`.

Following the tutorial (http://electron.atom.io/docs/v0.34.0/tutorial/quick-start/) I added 
* `main.js`
* `index.html`

Added those env vars (dont' know if they are really necessary):
```
set npm_config_disturl=https://atom.io/download/atom-shell
set npm_config_target=0.34.0
set npm_config_arch=x64
set npm_config_runtime=electron
```

Kicked off build of `node-gdal` (with `"gdal": "github:naturalatlas/node-gdal#win-node-4.2.1"` in `package.json`), because above `npm install` didn't put it into `node_modules` before:
```
npm install gdal
```

Then 
```
node_modules\.bin\electron-rebuild.cmd --version 0.34.0 --node-module-version 0.0.1
```

Then installed the prebuilt `electron.exe`:
```
npm install electron-prebuilt
```

Then added to `index.html`:
```
var gdal=require('gdal');
var dataset = gdal.open("c:/<PATH/TO/A/sample.shp");
var layer = dataset.layers.get(0);
document.write(layer.features.count());
```

Running
```
node_modules\electron-prebuilt\dist\electron.exe .
```

openend the electron app and showed the shapefile's correct feature count.

**Comment by TimJMartin** [comment]
Hey @BergWerkGIS I had started writing a simple app for you and then you solved it!

Let me give this a go and report back

**Comment by TimJMartin** [comment]
@BergWerkGIS 

IT WORKS!!!! 

My first 2 attempts failed with an error in the electron app console, even though everything built and installed fine.

So thought I would give it one more try and this time it worked.

This is awesome news as I can now build nice GUIs  for translating/loading our data.

Thank you so much for your time and effort on this.

**Comment by BergWerkGIS** [comment]
@TimJMartin Great! Good teamwork.

**Comment by brianreavis** [comment]
Awesome work @BergWerkGIS. Is [win-node-4.2.1](https://github.com/naturalatlas/node-gdal/tree/win-node-4.2.1) something we should merge now?

**Comment by BergWerkGIS** [comment]
@brianreavis Y, I think it can be merged, but would suggest, that we remove `iojs@3.3.1` from the build matrix.
What's your take on this?
Do you think a lot of people would like to use it with that version?

**Comment by brianreavis** [comment]
Works for me. I think most people using io.js have probably already upgraded to node 4.x. And in the case of Electron, it looks like `electron-rebuild` is the standard practice anyway... so no need to go crazy making prebuilt binaries.

**Comment by TimJMartin** [comment]
@brianreavis @BergWerkGIS it seems from Electron v0.33 now ships with Node 4.1.0 so from an electron POV i don't think supporting v3.3.1 is necessary (source: http://blog.atom.io/2015/10/15/2015-whats-new-in-electron.html).

**Comment by brianreavis** [comment]
@TimJMartin Sweet. On that note, going forward with node's new aggressive release strategy I think we're going to have troubles keeping up with the pre-built binary strategy. I'm thinking we need to either provide them just for LTS releases, or split out GDAL build (along the lines of #75)

**Comment by TimJMartin** [comment]
@brianreavis totally agree. 

From a novice point of view building from source is a bit scary and requires people to have software like Visual Studio etc installed and setup. If it is clearly documented then its relatively straight forward but some people are also restricted in what software they can install so may not to be an option.

So supporting the LTS and being able to do npm install gdal is I think the best way forward.
