### ISSUE TITLE
Plan to expose GDAL Dataset CreateCopy() ?

### ISSUE THREAD

**Issue by GretaCB** [naturalatlas/node-gdal#130]
Hi @brandonreavis @brianreavis ,

Been a while :) Hope you both are well. 

This ticket is somewhat related to https://github.com/naturalatlas/node-gdal/issues/67. Was wondering if you have plans to expose [the GDAL Dataset CreateCopy() function](http://www.gdal.org/classGDALDriver.html#a2c897da2a6e25169cccc49ef48797ce1) in node-gdal.

Based on the docs I linked to above, looks like the CreateCopy() function is what `gdal_translate` uses. I've noticed that if you use the `gdal_translate` utility on a compressed file, it will automatically create a copy that is decompressed. 

Ultimately, I'm looking to create a copy that re-encodes as TILED+uncompressed. Any ideas if the CreateCopy function will have the same result?

cc @springmeyer

**Comment by brandonreavis** [comment]
The `CreateCopy()` method is on the `GDALDriver` class and not the `GDALDataset` class, and it is already exposed here: http://naturalatlas.github.io/node-gdal/classes/gdal.Driver.html#method-createCopy.

It should work with something like this:
```js
function makeDecompressedCopy(filename, ds) { 
    var driver = gdal.drivers.get('GTiff');
    return driver.createCopy(filename, ds, false, {"COMPRESS": "NONE", "TILED": "YES"});
}
```
Hopefully this does what you want to do!

**Comment by GretaCB** [comment]
Bah, I overlooked that in the docs. Thank you @brandonreavis !

**Comment by GretaCB** [comment]
@brandonreavis Attempting to use the createCopy function like so is throwing [`String list must be an array or object`](https://github.com/naturalatlas/node-gdal/blob/master/src/utils/string_list.cpp#L51):

```
 try { ds = gdal.open(infile); }
 catch (err) { return callback(err); }
  
 var driver = gdal.drivers.get('GTiff');
  
 try { driver.createCopy("/Users/carol/dev/preprocessorcerer/decompressed.tif", ds, false, {"COMPRESS": "NONE", "TILED": "YES"}); }
 catch (err) { return callback(err); }
```

Do I need to be sending the filename param some other way?

**Comment by brianreavis** [comment]
Hmm, it looks like the documentation for `createCopy` doesn't match up with the implementation ([source](https://github.com/naturalatlas/node-gdal/blob/5b302e1acd4478e410e7b7a499aa890352ce07c3/src/gdal_driver.cpp#L348-L350)). Try this for now:
```js

 try { driver.createCopy("/Users/carol/dev/preprocessorcerer/decompressed.tif", ds, {"COMPRESS": "NONE", "TILED": "YES"}); }
 catch (err) { return callback(err); }
```

**Comment by GretaCB** [comment]
Hey @brandonreavis , thanks for the quick response.

Just tried it again with a few param variations and a few different files, but getting `[Error: Error copying dataset]`. [Looks like the Dataset is being created ok](https://github.com/naturalatlas/node-gdal/blob/5b302e1acd4478e410e7b7a499aa890352ce07c3/src/gdal_driver.cpp#L337), but something seems to possibly go awry somewhere [in here](https://github.com/naturalatlas/node-gdal/blob/5b302e1acd4478e410e7b7a499aa890352ce07c3/src/gdal_driver.cpp#L358-L361).

I also can't seem to find a test for this function to compare (apologies if I overlooked this as well).

**Comment by brandonreavis** [comment]
I'll write up a test and fix the missing `strict` argument tonight - we must have overlooked that. In the meantime, if you call `gdal.verbose() ` sometime before you try to create the copy does it print out anything useful to the console? Thats a pretty big raster... I wonder if it's memory related.

**Comment by GretaCB** [comment]
@brandonreavis gdal.verbose() results:

```
ERROR 4: Attempt to create new tiff file `/Users/carol/dev/preprocessorcerer/decompressed.tif' failed: No such file or directory
```
But the file definitely does exist. Also, been seeing the dataset error for smaller TIFFs as well.

**Comment by brandonreavis** [comment]
Just to confirm: the folder `/Users/carol/dev/preprocessorcerer/` already exists, right? Typically thats the problem when that error shows up, but i vaguely remember getting the same error for something not as intuitive.

**Comment by GretaCB** [comment]
@brandonreavis bingo. I had a typo.

Thank you! The tif was succesfully decompressed.

**Comment by GretaCB** [comment]
@brandonreavis I'm noticing that creating a copy is consistently creating empty tiffs (gdalinfo returns the same info, but the decompressed files show no data if viewed). Are you noticing the same thing?

**Comment by BergWerkGIS** [comment]
@GretaCB what is the file size of the created tiff im comparison to the original tiff?

You could run a checksum test on the result tiff, if there is any data in it (return value >0):
* `-checksum` if you use `gdalinfo` command line
* [`gdal.checksumImage`](http://naturalatlas.github.io/node-gdal/classes/gdal.html#method-checksumImage) if you use `node-gdal`

**Comment by BergWerkGIS** [comment]
@brandonreavis /cc @GretaCB 

I think there might be a problem in `node-gdal`.
I tried several TIFFs (from a few KB to a few GB in size) and for all `createCopy` (`GDALDataset *ds = raw->CreateCopy(filename.c_str(), raw_ds, strict, options.get(), NULL, NULL);`) creates a new dataset, but the values don't get copied.

e.g.: for http://download.osgeo.org/geotiff/samples/gdal_eg/cea.tif I get

<pre>
λ node index cea.tif
cea.tif
opening source
<b>checksum: 39108</b>
copying...
copy finished
opening copy
<b>checksum: 0</b>
</pre>

from this script:

```js
var gdal = require('gdal');

var infile = process.argv[2];
var outfile = infile + '-copy.tif';
console.log(infile);

/*
var copyoptions = [
	"BIGTIFF=YES",
	//"COMPRESS=NONE",
	"TILED=YES",
	"BLOCKXSIZE=512",
	"BLOCKYSIZE=512"
];
*/
var copyoptions = {
	"BIGTIFF": "YES",
	//"COMPRESS":"NONE",
	"TILED": "YES",
	"BLOCKXSIZE": "512",
	"BLOCKYSIZE": "512"
};

function makeDecompressedCopy(callback) {

	var ds;
	try {
		console.log('opening source');
		ds = gdal.open(infile);
		ds.bands.forEach(function (band) {
			console.log('checksum:', gdal.checksumImage(band));
		});
	}

	catch (err) {
		return callback('gdal open: ' + err);
	}

	var driver = gdal.drivers.get('GTiff');

	try {
		console.log('copying...');
		//driver.createCopy(outfile, ds);
		driver.createCopy(outfile, ds, copyoptions);
		console.log('copy finished');
		callback(null);
	}
	catch (err) {
		return callback('createCopy: ' + err);
	}
}

makeDecompressedCopy(function (err) {
	if (err) {
		console.log(err);
		process.exit(1);
	}

	try {
		console.log('opening copy')
		var ds = gdal.open(outfile);
		ds.bands.forEach(function (band) {
			console.log('checksum:', gdal.checksumImage(band));
		});
	}
	catch (err) {
		console.log('err:', err);
		process.exit(1);
	}
});
```

**Comment by BergWerkGIS** [comment]
GOT IT!!!

The missing piece was `ds.close()` and `dscopy.close()`.

<pre>
λ node index2 cea.tif
cea.tif
opening source
<b>checksum: 39108</b>
copying...
<b>dscopy checksum: 39108</b>
copy finished
opening copy
<b>opened copy checksum: 39108</b>
</pre>

```js
var gdal = require('gdal');

var infile = process.argv[2];
var outfile = infile + '-copy.tif';
console.log(infile);

var copyoptions = {
	"BIGTIFF": "YES",
	"COMPRESS":"NONE",
	"TILED": "YES",
	"BLOCKXSIZE": "512",
	"BLOCKYSIZE": "512"
};

function makeDecompressedCopy(callback) {

	var ds;
	try {
		console.log('opening source');
		ds = gdal.open(infile);
		ds.bands.forEach(function (band) {
			console.log('checksum:', gdal.checksumImage(band));
		});
	}

	catch (err) {
		return callback('gdal open: ' + err);
	}

	var driver = gdal.drivers.get('GTiff');

	try {
		console.log('copying...');
		var dscopy = driver.createCopy(outfile, ds, copyoptions);
		if (gdal.lastError) {
			console.log(gdal.lastError);
		}
		dscopy.bands.forEach(function (band) {
			console.log('dscopy checksum:', gdal.checksumImage(band));
		});
		ds.close();
		dscopy.close();
		console.log('copy finished');
		callback(null);
	}
	catch (err) {
		return callback('createCopy: ' + err);
	}
}

makeDecompressedCopy(function (err) {
	if (err) {
		console.log(err);
		process.exit(1);
	}

	try {
		console.log('opening copy')
		var ds = gdal.open(outfile);
		ds.bands.forEach(function (band) {
			console.log('opened copy checksum:', gdal.checksumImage(band));
		});
	}
	catch (err) {
		console.log('err:', err);
		process.exit(1);
	}
});
```

**Comment by brandonreavis** [comment]
@BergWerkGIS nice work! Sorry for not thinking about the `.close()` method sooner haha. It's awesome when you spend a bunch of time and then realize it is something silly like that. I've definitely done the same thing before.

**Comment by BergWerkGIS** [comment]
@brandonreavis no worries, always great when the :bulb: switches on.

**Comment by springmeyer** [comment]
Awesome work on this everyone :) To recap:

  - `driver.createCopy` exists and works great
  - you need to remember to close the datasets
  - an example of things working can be seen over at https://github.com/mapbox/preprocessorcerer/pull/45
  - there was some concern that small images were not copying right, but that turns out to be an apple preview.app bug.

Closing!

**Comment by mfrontela** [comment]
Hello,
First of all, I have found this issue trail very helpful. I'm wondering, could someone indicate how to properly form the options object that is passed into the createCopy function, please?
 What I need is to translate a .tif file into a bin file (UInt16 type), and as well as into a png file (also UInt16 type); following all of your comments, as well as the help from gdal_convert, this is the piece of code I wrote:
var gdal = require("gdal");
var dataset = gdal.open("path_to_tif_file/" + "MyFile.tif");
var copyOptions ={
  "TYPE": "UInt16"
};
try { 
  var driver = gdal.drivers.get("ENVI");
  driver.createCopy("path_to_saving_bin_file/" + "bin_filename", dataset, copyOptions); 
  driver = gdal.drivers.get("PNG");
  driver.createCopy("path_to_saving_png_file/" + "png_filename", dataset, copyOptions); 
}
catch (err) { 
  return console.log(err); 
}
The issue I'm experiencing is: MyTif.tif file is ~18Mb, after executing this code, the converted bin and png files are 1Kb and 8Kb in size, and thus nothing is being translated properly. I'm thinking I'm missing arguments in the copyOptions object? or how I built the copyOptions object is wrong?

Any guidance is greatly appreciated.
M.
