### ISSUE TITLE
Geometry.fromWKB  is broken

### ISSUE THREAD

**Issue by OferE** [naturalatlas/node-gdal#149]
Hi,

I'm trying to read a buffer taken from postgis into geometry using the following code:
```js
...
client.query('SELECT ST_AsEWKB(geom) as geom FROM tiles WHERE id = $1', ['1'], function(err, result) {
...
var res = result.rows[0].geom;
var res1 = gdal.Geometry.fromWKB(res);
```
and i am getting the following error on res:
```
Error: Argument must be a buffer object
```
I checked and res is a Buffer...

I also checked it using a raw buffer i created and i get the same error message.

It seems like the type check inside gdal_geometry.cpp is broken.

Thanks,
Ofer

**Comment by OferE** [comment]
i also tried the following:
gdal.Geometry.fromWKB(res1.toWKB())

where res1 is a valid geometry....

**Comment by brandonreavis** [comment]
You're right, it seems that newer versions of node return "Uint8Array" instead of "Buffer" when GetConstructorName is called on a buffer, but they still seem to work the same way. We will soon push out a new version with the fix.

I've been using fromWKB() with buffers from PostGIS too, so I'm surprised I didn't catch this sooner. Thanks!

**Comment by OferE** [comment]
Thanks for the quick response!
This module is awesome.

**Comment by OferE** [comment]
Hi,
R u going to release npm update or should i pull the tree?

**Comment by brandonreavis** [comment]
Hey Ofer,
Sorry releasing this took forever, but the latest version (0.9.0) is now out and it is fixed.

**Comment by OferE** [comment]
thanks!

On Tue, Mar 29, 2016 at 9:22 AM, Brandon Reavis <notifications@github.com>
wrote:

> Hey Ofer,
> Sorry releasing this took forever, but the latest version (0.9.0) is now
> out and it is fixed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/naturalatlas/node-gdal/issues/149#issuecomment-202735493>
>



-- 
Regards,
Ofer Eliassaf
