### ISSUE TITLE
MapInfo Driver

### ISSUE THREAD

**Issue by DemersM** [naturalatlas/node-gdal#150]
Hi!

Before giving a try to node-gdal, I would like to know if MapInfo Driver is implemented because I dont see it listed in the readme.

Thank you!

**Comment by jdesboeufs** [comment]
MapInfo TAB and MIF/MID are supported natively through GDAL, so it's supported by node-gdal ;)

**Comment by stev-0** [comment]
It's not mentioned in the list of bundled formats however. Excuse my ignorance, but is there something else that has to be implemented to make it available / register it?

**Comment by brianreavis** [comment]
Actually, it does seem we have a problem here. In the build configuration we define `MITAB_ENABLED=1`:
https://github.com/naturalatlas/node-gdal/blob/master/deps/libgdal/libgdal_formats.gypi#L169

Yet, "ogrregisterall.cpp" expects `TAB_ENABLED` ([here](https://github.com/naturalatlas/node-gdal/blob/e9dfb55a9699593483c4e4d836e805200b36c3d6/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrregisterall.cpp#L50))

I'll see if I can get this fixed up.
