### ISSUE TITLE
Error when installing package on OS X El Capitan 10.11.3, node 5.3.0, npm 3.3.12

### ISSUE THREAD

**Issue by ghing** [naturalatlas/node-gdal#151]
When I try to install the package with `npm install gdal@0.4.4` I get the following output:

```
# Previous, long console output supressed ...
LIBTOOL-STATIC Release/gdal_ogr_wasp_frmt.a
  CXX(target) Release/obj.target/gdal/src/utils/fast_buffer.o
Failed to execute 'node-gyp build --fallback-to-build --module=/Users/ghing/workspace/census-boundaries/node_modules/gdal/lib/binding/gdal.node --module_name=gdal --module_path=/Users/ghing/workspace/census-boundaries/node_modules/gdal/lib/binding' (1)
```

I've attached my [npm-debug.log](https://github.com/naturalatlas/node-gdal/files/116018/npm-debug.log.txt) as well as my [stderr output](https://github.com/naturalatlas/node-gdal/files/116017/errs.txt).

**Comment by brianreavis** [comment]
Why 0.4.4? This old version uses an old version of [nan](https://github.com/nodejs/nan) that won't work with node 5.3. Try out the latest version of node-gdal: `npm install gdal@0.8.0`

**Comment by ghing** [comment]
@brianreavis 0.4.4 is a dependency of [shp2json](https://github.com/substack/shp2json).  I'll try installing 0.8.0.  I'm pretty new to the packaging community.  What's the practice for recommending a dependency update to an upstream package?

**Comment by ghing** [comment]
Installing 0.8.0 seemed to work.  Closing this and will reach out to the shp2json developers.

**Comment by brianreavis** [comment]
Ahhhh gotcha. Yea, pull requesting on [shp2json](https://github.com/ghing/shp2json) is the way to go. Thanks for taking care of that!
