### ISSUE TITLE
Not loading all drivers

### ISSUE THREAD

**Issue by stev-0** [naturalatlas/node-gdal#161]
I am using the Heroku GFAL buildpack here (based on 1.11) https://github.com/mojodna/heroku-buildpack-gdal

On running ogrinfo --formats I get a number of vector formats including `-> "MapInfo File" (read/write)` which is what I am interested in.

However, on running in node:

    var gdal = require("gdal");
    console.log(gdal.drivers.getNames());

Mapinfo does not appear in the list, nor TAB, nor many other vector formats reported by ogrinfo.

I can't load the files either.

Is ogrinfo --formats broadly equivalent to gdal.drivers.getNames(). If so it would seem that node-gdal is not loading all drivers for some reason

**Comment by brianreavis** [comment]
By default, `node-gdal` uses its own version of GDAL which comes with its own set of drivers. If you want to use system GDAL/drivers, install using:
```sh
$ npm install gdal --build-from-source --shared_gdal
```
