### ISSUE TITLE
Upgrade to GDAL 2.1.0

### ISSUE THREAD

**Issue by springmeyer** [naturalatlas/node-gdal#164]
GDAL 2.1.0 is due out soon (next days): https://trac.osgeo.org/gdal/wiki/Release/2.1.0-News.

Just letting everyone know that I will plan to upgrade node-gdal to it when it is out officially and then will release node-gdal 0.9.2.

/cc @BergWerkGIS @brianreavis @brandonreavis @GretaCB

**Comment by springmeyer** [comment]
GDAL 2.1.0 is now out. Going to be taking a look asap at upgrading and getting node-gdal@0.9.2 released.

**Comment by springmeyer** [comment]
#166 is done, commencing with tag and release // @brandonreavis @brianreavis @GretaCB @BergWerkGIS

**Comment by brianreavis** [comment]
@springmeyer Awesome!
