### ISSUE TITLE
`npm install` error

### ISSUE THREAD

**Issue by eric79** [naturalatlas/node-gdal#167]
I am getting the following error when I attempt to install `gdal` via `npm` on my Windows machine:

    $ npm install gdal

    > gdal@0.9.1 preinstall C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935
    > npm install node-pre-gyp

    > gdal@0.9.1 preinstall C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935\node_modules\.staging\gdal-42cc7b10
    > npm install node-pre-gyp

    > gdal@0.9.1 preinstall C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935\node_modules\.staging\gdal-42cc7b10\node_modules\.staging\gdal-dd8a6d02
    > npm install node-pre-gyp

    > gdal@0.9.1 preinstall C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935\node_modules\.staging\gdal-42cc7b10\node_modules\.staging\gdal-dd8a6d02\node_modules\.staging\gdal-7b5e620e
    > npm install node-pre-gyp

    > gdal@0.9.1 preinstall C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935\node_modules\.staging\gdal-42cc7b10\node_modules\.staging\gdal-dd8a6d02\node_modules\.staging\gdal-7b5e620e\node_modules\.staging\gdal-1a40ce2b
    > npm install node-pre-gyp

    > gdal@0.9.1 preinstall C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935\node_modules\.staging\gdal-42cc7b10\node_modules\.staging\gdal-dd8a6d02\node_modules\.staging\gdal-7b5e620e\node_modules\.staging\gdal-1a40ce2b\node_modules\.staging\gdal-dcffef46
    > npm install node-pre-gyp

    > gdal@0.9.1 preinstall C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935\node_modules\.staging\gdal-42cc7b10\node_modules\.staging\gdal-dd8a6d02\node_modules\.staging\gdal-7b5e620e\node_modules\.staging\gdal-1a40ce2b\node_modules\.staging\gdal-dcffef46\node_modules\.staging\gdal-b8567002
    > npm install node-pre-gyp

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
    npm ERR! node v6.0.0
    npm ERR! npm  v3.8.6
    npm ERR! code ELIFECYCLE

    npm ERR! gdal@0.9.1 preinstall: `npm install node-pre-gyp`
    npm ERR! Exit status 3221226519
    npm ERR!
    npm ERR! Failed at the gdal@0.9.1 preinstall script 'npm install node-pre-gyp'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the gdal package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm install node-pre-gyp
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs gdal
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls gdal
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935\node_modules\.staging\gdal-42cc7b10\node_modules\.staging\gdal-dd8a6d02\node_modules\.staging\gdal-7b5e620e\node_modules\.staging\gdal-1a40ce2b\npm-debug.log
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
    npm ERR! node v6.0.0
    npm ERR! npm  v3.8.6
    npm ERR! code ELIFECYCLE

    npm ERR! gdal@0.9.1 preinstall: `npm install node-pre-gyp`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the gdal@0.9.1 preinstall script 'npm install node-pre-gyp'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the gdal package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm install node-pre-gyp
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs gdal
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls gdal
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935\node_modules\.staging\gdal-42cc7b10\node_modules\.staging\gdal-dd8a6d02\node_modules\.staging\gdal-7b5e620e\npm-debug.log
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
    npm ERR! node v6.0.0
    npm ERR! npm  v3.8.6
    npm ERR! code ELIFECYCLE

    npm ERR! gdal@0.9.1 preinstall: `npm install node-pre-gyp`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the gdal@0.9.1 preinstall script 'npm install node-pre-gyp'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the gdal package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm install node-pre-gyp
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs gdal
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls gdal
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935\node_modules\.staging\gdal-42cc7b10\node_modules\.staging\gdal-dd8a6d02\npm-debug.log
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
    npm ERR! node v6.0.0
    npm ERR! npm  v3.8.6
    npm ERR! code ELIFECYCLE

    npm ERR! gdal@0.9.1 preinstall: `npm install node-pre-gyp`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the gdal@0.9.1 preinstall script 'npm install node-pre-gyp'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the gdal package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm install node-pre-gyp
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs gdal
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls gdal
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935\node_modules\.staging\gdal-42cc7b10\npm-debug.log
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
    npm ERR! node v6.0.0
    npm ERR! npm  v3.8.6
    npm ERR! code ELIFECYCLE

    npm ERR! gdal@0.9.1 preinstall: `npm install node-pre-gyp`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the gdal@0.9.1 preinstall script 'npm install node-pre-gyp'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the gdal package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm install node-pre-gyp
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs gdal
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls gdal
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\eburns\Dev\node_modules\.staging\gdal-e027c935\npm-debug.log
    vwf@0.0.0 C:\Users\eburns\Dev
    `-- node-pre-gyp@0.6.27

    npm WARN vwf@0.0.0 license should be a valid SPDX license expression
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gdal"
    npm ERR! node v6.0.0
    npm ERR! npm  v3.8.6
    npm ERR! code ELIFECYCLE

    npm ERR! gdal@0.9.1 preinstall: `npm install node-pre-gyp`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the gdal@0.9.1 preinstall script 'npm install node-pre-gyp'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the gdal package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm install node-pre-gyp
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs gdal
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls gdal
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\eburns\Dev\npm-debug.log

Unfortunately, it looks liek the `npm-debug.log` that it mentions is deleted upon the process ending, so I wasn't able to inspect it.

Any ideas what could be causing this?

**Comment by brianreavis** [comment]
This seems to be a problem with NPM. Can you try what's mentioned here: https://github.com/mapnik/node-mapnik/issues/630

**Comment by eric79** [comment]
That seems better but not quite there:

    $ npm install gdal
    (node:38732) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

    > gdal@0.9.1 preinstall C:\Users\eburns\Dev\node_modules\.staging\gdal-9ae2b74f5f3ac08fd4b2de61b9127af9
    > npm install node-pre-gyp

    (node:30540) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
    gdal@0.9.1 C:\Users\eburns\Dev\node_modules\.staging\gdal-9ae2b74f5f3ac08fd4b2de61b9127af9
    └─┬ node-pre-gyp@0.6.27
      ├─┬ mkdirp@0.5.1
      │ └── minimist@0.0.8
      ├─┬ nopt@3.0.6
      │ └── abbrev@1.0.7
      ├─┬ npmlog@2.0.3
      │ ├── ansi@0.3.1
      │ ├─┬ are-we-there-yet@1.1.2
      │ │ ├── delegates@1.0.0
      │ │ └── readable-stream@2.1.2
      │ └─┬ gauge@1.2.7
      │   ├── has-unicode@2.0.0
      │   ├─┬ lodash.pad@4.3.0
      │   │ ├── lodash._baseslice@4.0.0
      │   │ └── lodash.tostring@4.1.2
      │   ├── lodash.padend@4.4.0
      │   └── lodash.padstart@4.4.0
      ├─┬ rc@1.1.6
      │ ├── deep-extend@0.4.1
      │ ├── ini@1.3.4
      │ ├── minimist@1.2.0
      │ └── strip-json-comments@1.0.4
      ├─┬ request@2.72.0
      │ ├── aws-sign2@0.6.0
      │ ├─┬ aws4@1.3.2
      │ │ └─┬ lru-cache@4.0.1
      │ │   ├── pseudomap@1.0.2
      │ │   └── yallist@2.0.0
      │ ├─┬ bl@1.1.2
      │ │ └── readable-stream@2.0.6
      │ ├── caseless@0.11.0
      │ ├─┬ combined-stream@1.0.5
      │ │ └── delayed-stream@1.0.0
      │ ├── extend@3.0.0
      │ ├── forever-agent@0.6.1
      │ ├─┬ form-data@1.0.0-rc4
      │ │ └── async@1.5.2
      │ ├─┬ har-validator@2.0.6
      │ │ ├─┬ chalk@1.1.3
      │ │ │ ├── ansi-styles@2.2.1
      │ │ │ ├── escape-string-regexp@1.0.5
      │ │ │ ├─┬ has-ansi@2.0.0
      │ │ │ │ └── ansi-regex@2.0.0
      │ │ │ ├── strip-ansi@3.0.1
      │ │ │ └── supports-color@2.0.0
      │ │ ├─┬ commander@2.9.0
      │ │ │ └── graceful-readlink@1.0.1
      │ │ ├─┬ is-my-json-valid@2.13.1
      │ │ │ ├── generate-function@2.0.0
      │ │ │ ├─┬ generate-object-property@1.2.0
      │ │ │ │ └── is-property@1.0.2
      │ │ │ ├── jsonpointer@2.0.0
      │ │ │ └── xtend@4.0.1
      │ │ └─┬ pinkie-promise@2.0.1
      │ │   └── pinkie@2.0.4
      │ ├─┬ hawk@3.1.3
      │ │ ├── boom@2.10.1
      │ │ ├── cryptiles@2.0.5
      │ │ ├── hoek@2.16.3
      │ │ └── sntp@1.0.9
      │ ├─┬ http-signature@1.1.1
      │ │ ├── assert-plus@0.2.0
      │ │ ├─┬ jsprim@1.2.2
      │ │ │ ├── extsprintf@1.0.2
      │ │ │ ├── json-schema@0.2.2
      │ │ │ └── verror@1.3.6
      │ │ └─┬ sshpk@1.8.3
      │ │   ├── asn1@0.2.3
      │ │   ├── assert-plus@1.0.0
      │ │   ├─┬ dashdash@1.13.1
      │ │   │ └── assert-plus@1.0.0
      │ │   ├── ecc-jsbn@0.1.1
      │ │   ├─┬ getpass@0.1.6
      │ │   │ └── assert-plus@1.0.0
      │ │   ├── jodid25519@1.0.2
      │ │   ├── jsbn@0.1.0
      │ │   └── tweetnacl@0.13.3
      │ ├── is-typedarray@1.0.0
      │ ├── isstream@0.1.2
      │ ├── json-stringify-safe@5.0.1
      │ ├─┬ mime-types@2.1.11
      │ │ └── mime-db@1.23.0
      │ ├── node-uuid@1.4.7
      │ ├── oauth-sign@0.8.1
      │ ├── qs@6.1.0
      │ ├── stringstream@0.0.5
      │ ├── tough-cookie@2.2.2
      │ └── tunnel-agent@0.4.2
      ├─┬ rimraf@2.5.2
      │ └─┬ glob@7.0.3
      │   ├── inflight@1.0.4
      │   ├─┬ minimatch@3.0.0
      │   │ └─┬ brace-expansion@1.1.4
      │   │   ├── balanced-match@0.4.1
      │   │   └── concat-map@0.0.1
      │   └── path-is-absolute@1.0.0
      ├── semver@5.1.0
      ├─┬ tar@2.2.1
      │ ├── block-stream@0.0.9
      │ ├─┬ fstream@1.0.8
      │ │ └── graceful-fs@4.1.3
      │ └── inherits@2.0.1
      └─┬ tar-pack@3.1.3
        ├─┬ debug@2.2.0
        │ └── ms@0.7.1
        ├── fstream-ignore@1.0.4
        ├─┬ once@1.3.3
        │ └── wrappy@1.0.1
        ├─┬ readable-stream@2.0.6
        │ ├── core-util-is@1.0.2
        │ ├── isarray@1.0.0
        │ ├── process-nextick-args@1.0.6
        │ ├── string_decoder@0.10.31
        │ └── util-deprecate@1.0.2
        └── uid-number@0.0.6


    > gdal@0.9.1 install C:\Users\eburns\Dev\node_modules\gdal
    > node-pre-gyp install --fallback-to-build


    C:\Users\eburns\Dev\node_modules\gdal>if not defined npm_config_node_gyp (node "C:\Users\eburns\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

    C:\Users\eburns\Dev\node_modules\gdal>if not defined npm_config_node_gyp (node "C:\Users\eburns\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v48-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v48-win32-x64 )  else (node  configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v48-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v48-win32-x64 )
    gyp ERR! configure error
    gyp ERR! stack Error: Command failed: C:\Python27\python.exe -c import platform; print(platform.python_version());
    gyp ERR! stack
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:202:12)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
    gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
    gyp ERR! stack     at emitOne (events.js:96:13)
    gyp ERR! stack     at Socket.emit (events.js:188:7)
    gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:485:12)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\eburns\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\eburns\\Dev\\node_modules\\gdal\\lib\\binding\\node-v48-win32-x64\\gdal.node" "--module_name=gdal" "--module_path=C:\\Users\\eburns\\Dev\\node_modules\\gdal\\lib\\binding\\node-v48-win32-x64"
    gyp ERR! cwd C:\Users\eburns\Dev\node_modules\gdal
    gyp ERR! node -v v6.0.0
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v48-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v48-win32-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\eburns\Dev\node_modules\gdal\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
    node-pre-gyp ERR! System Windows_NT 6.1.7601
    node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\eburns\\Dev\\\node_modules\\gdal\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd C:\Users\eburns\Dev\node_modules\gdal
    node-pre-gyp ERR! node -v v6.0.0
    node-pre-gyp ERR! node-pre-gyp -v v0.6.27
    node-pre-gyp ERR! not ok
    Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v48-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v48-win32-x64' (1)
    npm WARN EPACKAGEJSON vwf@0.0.0 license should be a valid SPDX license expression
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\eburns\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "gdal"
    npm ERR! node v6.0.0
    npm ERR! npm  v3.3.12
    npm ERR! code ELIFECYCLE

    npm ERR! gdal@0.9.1 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the gdal@0.9.1 install script 'node-pre-gyp install --fallback-to-build'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the gdal package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-pre-gyp install --fallback-to-build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls gdal
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\eburns\Dev\npm-debug.log

**Comment by brianreavis** [comment]
Just now noticed you're on Node 6, which we don't support quite yet. If you want to track progress, subscribe here: https://github.com/naturalatlas/node-gdal/issues/168. Going to close this issue as the NPM issue isn't specific to node-gdal.

**Comment by eric79** [comment]
I'm seeing the same (or similar) issue in node v4.4.3.  (Ironically, it was that bug that prompted me to upgrade to v6.0.0).  I'll open a new issue for v4.4.3.
