### ISSUE TITLE
Node 6 Support

### ISSUE THREAD

**Issue by brianreavis** [naturalatlas/node-gdal#168]

**Comment by springmeyer** [comment]
I'll try to hit this now. I botched the publish for linux binaries - which I'm working on fixing - in the process I can enable node v6 and see if it builds.

**Comment by springmeyer** [comment]
https://github.com/naturalatlas/node-gdal/commit/abc5414fe8e984523764548e4804a91545cfda85 - watching the CI and then I'll re-commence tagging v0.9.2.

**Comment by springmeyer** [comment]
builds are looking good, but ran out of time to tag today. Will pick back up tomorrow.

**Comment by springmeyer** [comment]
Done, will be available in node-gdal@0.9.2
