### ISSUE TITLE
`npm install` error in node v4.4.3

### ISSUE THREAD

**Issue by eric79** [naturalatlas/node-gdal#169]
When I try to install `gdal` with node.js v4.4.3 (and npm v3.3.12), I get the following error:

```
$ npm install gdal

> gdal@0.9.1 preinstall C:\Users\eburns\Dev\node_modules\.staging\gdal-9ae2b74f5f3ac08fd4b2de61b9127af9
> npm install node-pre-gyp

gdal@0.9.1 C:\Users\eburns\Dev\node_modules\.staging\gdal-9ae2b74f5f3ac08fd4b2de61b9127af9
└─┬ node-pre-gyp@0.6.27
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├─┬ nopt@3.0.6
  │ └── abbrev@1.0.7
  ├─┬ npmlog@2.0.3
  │ ├── ansi@0.3.1
  │ ├─┬ are-we-there-yet@1.1.2
  │ │ ├── delegates@1.0.0
  │ │ └── readable-stream@2.1.2
  │ └─┬ gauge@1.2.7
  │   ├── has-unicode@2.0.0
  │   ├─┬ lodash.pad@4.3.0
  │   │ ├── lodash._baseslice@4.0.0
  │   │ └── lodash.tostring@4.1.2
  │   ├── lodash.padend@4.4.0
  │   └── lodash.padstart@4.4.0
  ├─┬ rc@1.1.6
  │ ├── deep-extend@0.4.1
  │ ├── ini@1.3.4
  │ ├── minimist@1.2.0
  │ └── strip-json-comments@1.0.4
  ├─┬ request@2.72.0
  │ ├── aws-sign2@0.6.0
  │ ├─┬ aws4@1.3.2
  │ │ └─┬ lru-cache@4.0.1
  │ │   ├── pseudomap@1.0.2
  │ │   └── yallist@2.0.0
  │ ├─┬ bl@1.1.2
  │ │ └── readable-stream@2.0.6
  │ ├── caseless@0.11.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@1.0.0-rc4
  │ │ └── async@1.5.2
  │ ├─┬ har-validator@2.0.6
  │ │ ├─┬ chalk@1.1.3
  │ │ │ ├── ansi-styles@2.2.1
  │ │ │ ├── escape-string-regexp@1.0.5
  │ │ │ ├─┬ has-ansi@2.0.0
  │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ ├── strip-ansi@3.0.1
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ commander@2.9.0
  │ │ │ └── graceful-readlink@1.0.1
  │ │ ├─┬ is-my-json-valid@2.13.1
  │ │ │ ├── generate-function@2.0.0
  │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ └── is-property@1.0.2
  │ │ │ ├── jsonpointer@2.0.0
  │ │ │ └── xtend@4.0.1
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.2.2
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.2
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.8.3
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├─┬ dashdash@1.13.1
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├─┬ getpass@0.1.6
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── jodid25519@1.0.2
  │ │   ├── jsbn@0.1.0
  │ │   └── tweetnacl@0.13.3
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.11
  │ │ └── mime-db@1.23.0
  │ ├── node-uuid@1.4.7
  │ ├── oauth-sign@0.8.2
  │ ├── qs@6.1.0
  │ ├── stringstream@0.0.5
  │ ├── tough-cookie@2.2.2
  │ └── tunnel-agent@0.4.3
  ├─┬ rimraf@2.5.2
  │ └─┬ glob@7.0.3
  │   ├── inflight@1.0.4
  │   ├─┬ minimatch@3.0.0
  │   │ └─┬ brace-expansion@1.1.4
  │   │   ├── balanced-match@0.4.1
  │   │   └── concat-map@0.0.1
  │   └── path-is-absolute@1.0.0
  ├── semver@5.1.0
  ├─┬ tar@2.2.1
  │ ├── block-stream@0.0.9
  │ ├─┬ fstream@1.0.8
  │ │ └── graceful-fs@4.1.3
  │ └── inherits@2.0.1
  └─┬ tar-pack@3.1.3
    ├─┬ debug@2.2.0
    │ └── ms@0.7.1
    ├── fstream-ignore@1.0.4
    ├─┬ once@1.3.3
    │ └── wrappy@1.0.1
    ├─┬ readable-stream@2.0.6
    │ ├── core-util-is@1.0.2
    │ ├── isarray@1.0.0
    │ ├── process-nextick-args@1.0.7
    │ ├── string_decoder@0.10.31
    │ └── util-deprecate@1.0.2
    └── uid-number@0.0.6


> gdal@0.9.1 install C:\Users\eburns\Dev\node_modules\gdal
> node-pre-gyp install --fallback-to-build


C:\Users\eburns\Dev\node_modules\gdal>if not defined npm_config_node_gyp (node "C:\Users\eburns\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\Users\eburns\Dev\node_modules\gdal>if not defined npm_config_node_gyp (node "C:\Users\eburns\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64 )  else (node  configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python27\python.exe -c import platform; print(platform.python_version());
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:213:12)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:477:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\eburns\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\eburns\\Dev\\node_modules\\gdal\\lib\\binding\\node-v46-win32-x64\\gdal.node" "--module_name=gdal" "--module_path=C:\\Users\\eburns\\Dev\\node_modules\\gdal\\lib\\binding\\node-v46-win32-x64"
gyp ERR! cwd C:\Users\eburns\Dev\node_modules\gdal
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\eburns\Dev\node_modules\gdal\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\eburns\\Dev\\node_modules\\gdal\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\eburns\Dev\node_modules\gdal
node-pre-gyp ERR! node -v v4.4.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.27
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64' (1)
npm WARN EPACKAGEJSON vwf@0.0.0 license should be a valid SPDX license expression
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\eburns\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "gdal"
npm ERR! node v4.4.3
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! gdal@0.9.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gdal@0.9.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gdal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls gdal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\eburns\Dev\npm-debug.log
```

**Comment by eric79** [comment]
Just in case the new version of `npm` was causing an issue, I rolled it back to v2.15.1, which installs w/ node.js v4.4.3.  Different, though similar results:

    $ npm install gdal
    npm WARN package.json vwf@0.0.0 license should be a valid SPDX license expression

    > gdal@0.9.1 preinstall C:\Users\eburns\Dev\node_modules\gdal
    > npm install node-pre-gyp

    npm WARN engineStrict Per-package engineStrict (found in this package's package.json)
    npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
    node-pre-gyp@0.6.27 node_modules\node-pre-gyp
    ├── semver@5.1.0
    ├── mkdirp@0.5.1 (minimist@0.0.8)
    ├── nopt@3.0.6 (abbrev@1.0.7)
    ├── tar@2.2.1 (block-stream@0.0.9, inherits@2.0.1, fstream@1.0.8)
    ├── npmlog@2.0.3 (ansi@0.3.1, gauge@1.2.7, are-we-there-yet@1.1.2)
    ├── rc@1.1.6 (ini@1.3.4, deep-extend@0.4.1, strip-json-comments@1.0.4, minimist@1.2.0)
    ├── rimraf@2.5.2 (glob@7.0.3)
    ├── tar-pack@3.1.3 (uid-number@0.0.6, readable-stream@2.0.6, fstream@1.0.8, once@1.3.3, debug@2.2.0, fstream-ignore@1.0.4)
    └── request@2.72.0 (oauth-sign@0.8.2, aws-sign2@0.6.0, tunnel-agent@0.4.3, forever-agent@0.6.1, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.1.0, bl@1.1.2, mime-types@2.1.11, aws4@1.3.2, form-data@1.0.0-rc4, hawk@3.1.3, combined-stream@1.0.5, http-signature@1.1.1, har-validator@2.0.6)

    > gdal@0.9.1 install C:\Users\eburns\Dev\node_modules\gdal
    > node-pre-gyp install --fallback-to-build


    C:\Users\eburns\Dev\node_modules\gdal>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

    C:\Users\eburns\Dev\node_modules\gdal>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64 )
    gyp ERR! configure error
    gyp ERR! stack Error: Command failed: C:\Python27\python.exe -c import platform; print(platform.python_version());
    gyp ERR! stack
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:213:12)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
    gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
    gyp ERR! stack     at emitOne (events.js:77:13)
    gyp ERR! stack     at Socket.emit (events.js:169:7)
    gyp ERR! stack     at Pipe._onclose (net.js:477:12)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\eburns\\Dev\\node_modules\\gdal\\lib\\binding\\node-v46-win32-x64\\gdal.node" "--module_name=gdal" "--module_path=C:\\Users\\eburns\\Dev\\node_modules\\gdal\\lib\\binding\\node-v46-win32-x64"
    gyp ERR! cwd C:\Users\eburns\Dev\node_modules\gdal
    gyp ERR! node -v v4.4.3
    gyp ERR! node-gyp -v v3.3.1
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\eburns\Dev\node_modules\gdal\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    node-pre-gyp ERR! System Windows_NT 6.1.7601
    node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\eburns\\Dev\\\node_modules\\gdal\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd C:\Users\eburns\Dev\node_modules\gdal
    node-pre-gyp ERR! node -v v4.4.3
    node-pre-gyp ERR! node-pre-gyp -v v0.6.27
    node-pre-gyp ERR! not ok
    Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64' (1)
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gdal"
    npm ERR! node v4.4.3
    npm ERR! npm  v2.15.1
    npm ERR! code ELIFECYCLE

    npm ERR! gdal@0.9.1 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the gdal@0.9.1 install script 'node-pre-gyp install --fallback-to-build'.
    npm ERR! This is most likely a problem with the gdal package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-pre-gyp install --fallback-to-build
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs gdal
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!
    npm ERR!     npm owner ls gdal
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\eburns\Dev\npm-debug.log

**Comment by brianreavis** [comment]
@BergWerkGIS Have you seen anything like this before? (Windows)

**Comment by springmeyer** [comment]
I just published v0.9.2 - can you try again with that version?

**Comment by eric79** [comment]
With v0.9.2, I get:

$ npm install gdal
    npm WARN package.json vwf@0.0.0 license should be a valid SPDX license expression

    > gdal@0.9.2 preinstall C:\Users\eburns\Dev\node_modules\gdal
    > npm install node-pre-gyp

    npm WARN engineStrict Per-package engineStrict (found in this package's package.json)
    npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
    node-pre-gyp@0.6.28 node_modules\node-pre-gyp
    ├── semver@5.1.0
    ├── nopt@3.0.6 (abbrev@1.0.7)
    ├── rc@1.1.6 (deep-extend@0.4.1, ini@1.3.4, strip-json-comments@1.0.4, minimist@1.2.0)
    ├── mkdirp@0.5.1 (minimist@0.0.8)
    ├── rimraf@2.5.2 (glob@7.0.3)
    ├── npmlog@2.0.3 (ansi@0.3.1, are-we-there-yet@1.1.2, gauge@1.2.7)
    ├── tar-pack@3.1.3 (uid-number@0.0.6, once@1.3.3, readable-stream@2.0.6, fstream-ignore@1.0.4, debug@2.2.0, fstream@1.0.9)
    ├── tar@2.2.1 (block-stream@0.0.9, inherits@2.0.1, fstream@1.0.9)
    └── request@2.72.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, forever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.1.0, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4, hawk@3.1.3, bl@1.1.2, http-signature@1.1.1, har-validator@2.0.6)

    > gdal@0.9.2 install C:\Users\eburns\Dev\node_modules\gdal
    > node-pre-gyp install --fallback-to-build

    node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/gdal/v0.9.2/node-v46-win32-x64.tar.gz
    node-pre-gyp ERR! Pre-built binaries not found for gdal@0.9.2 and node@4.4.3 (node-v46 ABI) (falling back to source compile with node-gyp)

    C:\Users\eburns\Dev\node_modules\gdal>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

    C:\Users\eburns\Dev\node_modules\gdal>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64 )
    gyp ERR! configure error
    gyp ERR! stack Error: Command failed: C:\Python27\python.exe -c import platform; print(platform.python_version());
    gyp ERR! stack
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:213:12)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
    gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
    gyp ERR! stack     at emitOne (events.js:77:13)
    gyp ERR! stack     at Socket.emit (events.js:169:7)
    gyp ERR! stack     at Pipe._onclose (net.js:477:12)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\eburns\\Dev\\node_modules\\gdal\\lib\\binding\\node-v46-win32-x64\\gdal.node" "--module_name=gdal" "--module_path=C:\\Users\\eburns\\Dev\\node_modules\\gdal\\lib\\binding\\node-v46-win32-x64"
    gyp ERR! cwd C:\Users\eburns\Dev\node_modules\gdal
    gyp ERR! node -v v4.4.3
    gyp ERR! node-gyp -v v3.3.1
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\eburns\Dev\node_modules\gdal\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    node-pre-gyp ERR! System Windows_NT 6.1.7601
    node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\eburns\\Dev\\node_modules\\gdal\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd C:\Users\eburns\Dev\node_modules\gdal
    node-pre-gyp ERR! node -v v4.4.3
    node-pre-gyp ERR! node-pre-gyp -v v0.6.28
    node-pre-gyp ERR! not ok
    Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\eburns\Dev\node_modules\gdal\lib\binding\node-v46-win32-x64' (1)
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gdal"
    npm ERR! node v4.4.3
    npm ERR! npm  v2.15.1
    npm ERR! code ELIFECYCLE

    npm ERR! gdal@0.9.2 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the gdal@0.9.2 install script 'node-pre-gyp install --fallback-to-build'.
    npm ERR! This is most likely a problem with the gdal package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-pre-gyp install --fallback-to-build
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs gdal
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!
    npm ERR!     npm owner ls gdal
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\eburns\Dev\npm-debug.log

It's notable that this time the first error message is:

    node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/gdal/v0.9.2/node-v46-win32-x64.tar.gz

I verified that I can download that file in my browser and that my npm `https-proxy` is set correctly.  Any thoughts?

**Comment by jwoyame** [comment]
The command that is failing is from configure.js of node-gyp:
```
C:\Python27\python.exe -c import platform; print(platform.python_version());
```

Something may be up with your Python install? Check out the Installation instructions at https://github.com/nodejs/node-gyp.

**Comment by eric79** [comment]
Thanks!  I have good news and bad news.  The bad news is that even after following those instructions to upgrade my python to the suggested version and install Visual Studio, etc, it still didn't build for me.  The good news is that I determined that it was our self-signed certificate in the certificate change which was leading `node-gyp` to fall back to the manually built version in the first place.  I temporarily told node-gyp to ignore the certs (I know ... that's madness, but I was desperate) by setting `NODE_TLS_REJECT_UNAUTHORIZED` to 0 and then running `npm install gdal`.

That appears to have worked.  Thanks for your help.
