### ISSUE TITLE
using node-gdal in electron app

### ISSUE THREAD

**Issue by Charmatzis** [naturalatlas/node-gdal#176]
Hi, I know that I there was and a previous issue mentioned that problem, but I haven't understand very well what should I do...... 
So let's start from the electron-quick-start in GitHub [electron-quick-start](https://github.com/electron/electron-quick-start).
Then I run `npm install` and then `npm install --save-dev electron-rebuild ` , so I can get my electron app ready.
After, I run `npm install gdal --save` which I had no problems with that also.

Then I have import into the project.json file 
this 

```
"binary": {
    "module_name": "gdal",
    "module_path": "./lib/binding/{node_abi}-{platform}-{arch}",
    "remote_path": "./{module_name}/v{version}/{toolset}/",
    "host": "https://mapbox-node-binary.s3.amazonaws.com",
    "package_name": "{node_abi}-{platform}-{arch}.tar.gz"
  },
```
Which is the binary paths.

The next step is to import 

```
var gdal = require("gdal");
var dataset = gdal.open("sample.tif");

console.log("number of bands: " + dataset.bands.count());
console.log("width: " + dataset.rasterSize.x);
console.log("height: " + dataset.rasterSize.y);
console.log("geotransform: " + dataset.geoTransform);
console.log("srs: " + (dataset.srs ? dataset.srs.toWKT() : 'null'));
```

that code into the render.js 

The error I get is 

ELECTRON_ASAR.js:158 Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\smthing\GitHub\electron-quick-start\node_modules\gdal\lib\binding\electron-v1.2-win32-x64\gdal.node

How do I create that gdal.node file?

**Comment by BergWerkGIS** [comment]
`gdal.node` was installed via `npm install gdal --save`.

This doesn't look right:
<pre>
node_modules\gdal\lib\binding\<b>electron-v1.2-win32-x64</b>\gdal.node
</pre>

Which directories are there in `node_modules\gdal\lib\binding`?

**Comment by BergWerkGIS** [comment]
That the directory tree on my machine:

![image](https://cloud.githubusercontent.com/assets/4549888/16329870/a1f5fe08-39e5-11e6-8001-3e04e8f25a29.png)

**Comment by Charmatzis** [comment]
@BergWerkGIS , nope, my directory is that to me..
"....\electron-quick-start\node_modules\gdal\lib\binding\electron-v1.2-win32-x64\gdal.node"

I have and a file electron-v1.2-win32-x64 which comes from 

```
"binary": {
    "host": "https://mapbox-node-binary.s3.amazonaws.com",
    "module_name": "gdal",
    "module_path": "./lib/binding/{node_abi}-{platform}-{arch}",
    "package_name": "{node_abi}-{platform}-{arch}.tar.gz",
    "remote_path": "./{module_name}/v{version}/{toolset}/"
  },
```

In the node-gdal project.json

**Comment by Charmatzis** [comment]
But I found a solution !!!!!!

clone the electron-quick-start from GitHub.

Then open the project.json and add 

```
 "dependencies": {
    "gdal":"^0.9.2"
  }
```

Then run [as it says here](http://electron.atom.io/docs/tutorial/using-native-node-modules/)

```
set npm_config_target=1.2.3
set npm_config_arch=x64
set npm_config_disturl=https://atom.io/download/atom-shell
set npm_config_runtime=electron
set npm_config_build_from_source=true
set HOME=~/.electron-gyp npm install
```


Then run `npm install`

Add some demo code in the index.html file in the solution 
e.g.

```

var gdal = require('gdal');
var dataset = gdal.open("C:/Somewhere/coast.shp");
var layer = dataset.layers.get(0);
document.write('The shapefile has: ' + layer.features.count() + ' features.');
```

Finally, run `npm start `

**And you see the results!!!!!!!**

PS. I will close this issue, but I will come back for installing the electron app....
