### ISSUE TITLE
Fail to set spatial reference to new GeoTIFF file

### ISSUE THREAD

**Issue by haoliangyu** [naturalatlas/node-gdal#180]
I try to set the geographic transformation and spatial reference to a GeoTIFF generated by node-gdal. Both of them is read from an existing .tif file:

``` javascript
// read an existing file and get its spatial reference
let dataset = gdal.open(filePath);
this.bandData = dataset.bands.get(1);
this.rasterSize = dataset.rasterSize;
this.geoTransform = dataset.geoTransform;
this.spatialReference = dataset.spatialReference;

// save the same spatial reference to a new file
let driver = gdal.drivers.get('GTiff');
let dataset = driver.create(savePath, this.rasterSize.x, this.rasterSize.y, 1, gdal.GDT_Byte);

let bandData = dataset.bands.get(1);
bandData.pixels.write(0, 0, this.rasterSize.x, this.rasterSize.y, data);

dataset.spatialReference = this.spatialReference;
dataset.geoTransform = this.geoTransform;
dataset.flush();
```

The data could be saved to the .tif file successfully. But when I open the raster file with QGIS, it shows that the raster file doesn't have any spatial reference information. Do I miss something when I try to save the spatial reference to file?

**Comment by brianreavis** [comment]
I think it's just a typo causing the problem. You should have `dataset.srs` instead of `dataset.spatialReference`. 
```js
dataset.spatialReference = this.spatialReference; // should be dataset.srs
dataset.geoTransform = this.geoTransform; 
dataset.flush();
```

For example: https://github.com/naturalatlas/node-gdal/blob/master/test/api_dataset.test.js#L317

**Comment by haoliangyu** [comment]
My mistake :-( Thanks for pointing out.
