### ISSUE TITLE
Segfault with an unknown SRS in suggestedWarpOutput()

### ISSUE THREAD

**Issue by mapsam** [naturalatlas/node-gdal#181]
Hello! I am using node-gdal to reproject tifs into web mercator. When a source tif with an unknown SRS is loaded into `gdal.suggestedWarpOutput()` the process stalls. Here's an example of what I'm doing:

```javascript
var soucePath = './path/to/source.tif';
var destPath = './path/to/destination.tif';
var cpus = require('os').cpus().length;
var warp_cache_max = 750; //MB
var gdal_cache_max = warp_cache_max * 3;
gdal.config.set('GDAL_CACHEMAX', gdal_cache_max.toString());

var src = gdal.open(sourcePath);

var bandCount = src.bands.count();
var dataType = src.bands.get(1).dataType;

var options = {
  src: src,
  s_srs: src.srs,
  t_srs: gdal.SpatialReference.fromEPSG(3857),
  memoryLimit: warp_cache_max * 1024 * 1024,
  multi: true,
  options: ['NUM_THREADS=' + cpus.toString()]
};

var info = gdal.suggestedWarpOutput(options); // this is it crashes with Segfault 11

// ... do things with info & output tif ...
```

I'd expect `gdal.suggestedWarpOutput()` to throw an error if the SRS is unsupported. 

#### Current work-around

The current workaround is to check the SRS prior to using `gdal.suggestedWarpOutput()` with the following added before defining `options` above:

```javascript
// identify EPSG, which will throw if srs is unsupported
src.srs.autoIdentifyEPSG();
```

It works, but I'm not 100% confident in the stop-gap and am curious if there's a better solution to preventing the segfault.

**Sample fixture**: [unsupported-srs.tif.zip](https://github.com/naturalatlas/node-gdal/files/435164/unsupported-srs.tif.zip)

**DiagnosticReport** from the crash on my local machine: https://gist.github.com/mapsam/9f19e009849d500b52ee55594bba3d28

**Comment by mapsam** [comment]
@springmeyer suggested [these lines](https://github.com/naturalatlas/node-gdal/blob/e9dfb55a9699593483c4e4d836e805200b36c3d6/src/gdal_warper.cpp#L342-L350) may be the culprit, where `s_srs->get()` is failing.

**Comment by mapsam** [comment]
`gdalinfo` output of the test file:

```
Driver: GTiff/GeoTIFF
Files: unsupported-srs.tif
Size is 49, 76
Coordinate System is:
PROJCS["Mercator MARS",
    GEOGCS["GCS_MARS",
        DATUM["D_MARS",
            SPHEROID["MARS",3396190,169.8944472236118]],
        PRIMEM["Reference_Meridian",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["latitude_of_origin",-35.72000122070312],
    PARAMETER["central_meridian",129.4499969482422],
    PARAMETER["scale_factor",0],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]]]
Origin = (-15648.000000000000000,-1817274.000000000000000)
Pixel Size = (606.979591836734699,-603.315789473684163)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  -15648.000,-1817274.000) 
Lower Left  (  -15648.000,-1863126.000) 
Upper Right (   14094.000,-1817274.000) 
Lower Right (   14094.000,-1863126.000) 
Center      (    -777.000,-1840200.000) 
Band 1 Block=49x76 Type=Byte, ColorInterp=Gray
  NoData Value=0
```

**Comment by brandonreavis** [comment]
Turns out the call to `GDALCreateGenImgProjTransformer()` [here](https://github.com/naturalatlas/node-gdal/blob/e9dfb55a9699593483c4e4d836e805200b36c3d6/src/gdal_warper.cpp#L355) was failing and returning null as it should, and then node-gdal was passing that null pointer to `GDALSuggestedWarpOutput()` which wreaked havoc. I just pushed a fix that will cause it to throw an error (`"Mercator_1SP with scale != 1.0 and latitude of origin != 0, not supported by PROJ.4."`) instead of hanging.

Thanks for the clean test example @mapsam!

**Comment by mapsam** [comment]
Lovely @brandonreavis! Thanks for the quick fix.

**Comment by springmeyer** [comment]
Thanks @brandonreavis - nice fix.

**Comment by springmeyer** [comment]
The test added for this is failing to throw with older GDAL versions:

```
not ok 475 gdal reprojectImage() should throw error if GDAL can't create transformer
  AssertionError: expected [Function] to throw an error
      at Function.assert.throws (node_modules/chai/lib/chai/interface/assert.js:1120:52)
      at Context.<anonymous> (test/api_warp.test.js:467:11)
```

**Comment by springmeyer** [comment]
failing test will be skipped now in 5d4b017.
