### ISSUE TITLE
Feature Request: Support GRIB driver

### ISSUE THREAD

**Issue by eschwartz** [naturalatlas/node-gdal#191]
Would it be possible to support the [GRIB](http://www.gdal.org/frmt_grib.html) driver for gdal?

I would really like to use this library, but our workflow depends heavily on reading and transforming grib files. I would be willing to help make this feature request possible, if someone could give me a little direction... :)

**Comment by eschwartz** [comment]
So I gave a stab at this, with very little understand of how any of this works :p

Here's what I did:
- Added `grib` to the `GDAL_FORMATS` var in deps/libgdal
- Ran `make clean` and `make` from the `deps/` dir, to reinstall gdal
- Ran `make rebuild` from the root dir

The final `make rebuild` resulted in an error like:

```
../deps/libgdal/gdal/frmts/grib/degrib18/degrib/grib2api.c:20:19: fatal error: grib2.h: No such file or directory
compilation terminated.
deps/libgdal/gyp-formats/libgdal_grib_frmt.target.mk:237: recipe for target 'Release/obj.target/libgdal_grib_frmt/deps/libgdal/gdal/frmts/grib/degrib18/degrib/grib2api.o' failed
```

There is in fact a file called `grib2.h`, but it's in 
```
/deps/libgdal/gdal/frmts/grib/degrib18/g2clib-1.0.4/grib2.h
```

I should note I know almost nothing about  gdal, C, or node-gyp. So I'm not super surprised it failed. Just thought I'd give some naive hacking a try.

**Comment by brianreavis** [comment]
GRIB  support was added in https://github.com/naturalatlas/node-gdal/releases/tag/v0.10.0
