### ISSUE TITLE
Raster Analysis

### ISSUE THREAD

**Issue by AlokBansal8** [naturalatlas/node-gdal#194]
I have a raster file and a set of vertices of a polygon and my objective is to find all the grids in the raster that lie within the boundary of the given polygon and do some statistical analysis like sum, mean, etc on the obtained grids (intersection).

**Comment by AlokBansal8** [comment]
@brandonreavis Please help.

**Comment by brandonreavis** [comment]
This is entirely possible, but the issues on github are more for reporting bugs and missing features. I would suggest stackoverflow for asking development help.

http://gis.stackexchange.com/questions/16657/clipping-raster-with-vector-layer-using-gdal

You will likely want to clip the source raster with a polygon then compute the stats on the clipped raster... this way you don't have to loop through the pixels manually with javascript. The `gdal.reprojectImage` method here http://naturalatlas.github.io/node-gdal/classes/gdal.html can help.

**Comment by brandonreavis** [comment]
Just to verify, you are doing `dest.close();` at the end somewhere, right?

**Comment by AlokBansal8** [comment]
Yes.

**Comment by AlokBansal8** [comment]
I think there should be examples of many of the functions of gdal library in the examples section.
