### ISSUE TITLE
Is it possible to use ogr2ogr with this module?

### ISSUE THREAD

**Issue by tsemerad** [naturalatlas/node-gdal#199]
I need to be able to run ogr2ogr commands in my node module, and I'll be deploying it to an environment where I can't separately install the ogr2ogr command line tool. I like how GDAL comes bundled with this library so that it works out of the box - does that mean I also have access to ogr2ogr?

Looking through the documentation, it doesn't appear to be the case. It looks like I can manually recreate what ogr2ogr does to an extent. However, I was hoping to be able to use ogr2ogr's powerful SQL functionality to rename and type cast fields like I do in the following command: 
```
ogr2ogr -f "GeoJSON" ./outputFile.geojson ./inputFile.shp -sql "SELECT CAST(isActive AS boolean) AS active) FROM inputFile"
```

**Comment by brandonreavis** [comment]
You are right that ogr2ogr isn't directly exposed, but much of its functionality is. Take a look at http://naturalatlas.github.io/node-gdal/classes/gdal.Dataset.html#method-executeSQL

That would be something like:
```js
var inputDataset = gdal.open('./inputFile.shp');
var inputLayer = inputDataset.executeSQL('SELECT CAST(isActive AS boolean) AS active) FROM inputFile');
var outputDataset = gdal.open('./outputFile.geojson', 'w', 'GeoJSON');
// ... then create outputLayer and add features to it from inputLayer
```

**Comment by tsemerad** [comment]
Thank you very much for the advice. That is exactly what I needed. I now have the following code which is working great:
```javascript
const inputDataset = gdal.open('./inputFile.shp')
const inputLayer = inputDataset.executeSQL('SELECT CAST(isActive AS boolean) AS active) FROM inputFile')
const outputDataset = gdal.open('./outputFile.geojson', 'w', 'GeoJSON')
const outputLayer = outputDataset.layers.create('myTableName', null, inputLayer.geomType)

inputLayer.features.forEach(feature => {
  outputLayer.features.add(feature)
})

outputLayer.flush()
outputDataset.close()
```

**Comment by brandonreavis** [comment]
Great! I'm glad that works!

I think the gdal GeoJSON driver is pretty flexible so what you did works, but for future reference you would probably want to set up the output schema before adding features to the output layer, and create the output feature specifically for the output layer.

Something like this:
```js
const inputDataset = gdal.open('./inputFile.shp')
const inputLayer = inputDataset.executeSQL('SELECT CAST(isActive AS boolean) AS active) FROM inputFile')
const outputDataset = gdal.open('./outputFile.geojson', 'w', 'GeoJSON')
const outputLayer = outputDataset.layers.create('myTableName', inputLayer.srs, inputLayer.geomType)

// set up output schema
inputLayer.fields.forEach(field => outputLayer.fields.add(new gdal.FieldDefn(field.name, field.type)));

inputLayer.features.forEach(feature => {
  // create feature specifically for the output layer
  const outputFeature = new gdal.Feature(outputLayer);
  outputFeature.setGeometry(feature.getGeometry());
  outputFeature.fields.set(feature.fields.toObject());
  outputLayer.features.add(outputFeature)
})

// outputLayer.flush() - this is unnecessary because the dataset gets flushed when it is closed
outputDataset.close()
```
