### ISSUE TITLE
Release v0.9.5: last release with node v0.10.x support

### ISSUE THREAD

**Issue by springmeyer** [naturalatlas/node-gdal#202]
I propose one last release with:

 - node v0.10.x support.
 - also node v8 support

To get node v0.10.x builds out, we'll need to stop using `npm-windows-upgrade` which recently dropped node v0.10.x support.

After that we can bump to v0.10.x and only support: node v4, 6, and 8.

/cc @brianreavis @BergWerkGIS

**Comment by jdesboeufs** [comment]
@brianreavis You just have to publish the npm package ;)

**Comment by brianreavis** [comment]
@jdesboeufs Hah yep. I'm just waiting for all the Windows builds to complete. I might have to kick it a few more times because it stops halfway through at NPM sometimes...

Trying to get these ones green now:
```
Environment: nodejs_version=8, msvs_toolset=12; Platform: x64
Environment: nodejs_version=6, msvs_toolset=14; Platform: x86
Environment: nodejs_version=6, msvs_toolset=14; Platform: x64
Environment: nodejs_version=8, msvs_toolset=14; Platform: x86
Environment: nodejs_version=8, msvs_toolset=14; Platform: x64
```

**Comment by jdesboeufs** [comment]
Still missing:

- [ ] Environment: nodejs_version=6, msvs_toolset=14; Platform: x64
- [ ] Environment: nodejs_version=8, msvs_toolset=14; Platform: x86

**Comment by brianreavis** [comment]
[0.9.6](https://github.com/naturalatlas/node-gdal/releases/tag/v0.9.6) is built and published.

https://ci.appveyor.com/project/brianreavis/node-gdal/build/727
https://travis-ci.org/naturalatlas/node-gdal/builds/266310443

**Comment by springmeyer** [comment]
Thank you for pushing this out @brianreavis!
