### ISSUE TITLE
gdal.config.set is not a function

### ISSUE THREAD

**Issue by AlokBansal8** [naturalatlas/node-gdal#207]
When I try to run multiple test files using jest, I get following error:

```cmd
 PASS  src/server/gis/common/value-calculator.test.js
 FAIL  src/server/gis/raster/index.test.js
  ● Test suite failed to run

    TypeError: gdal.config.set is not a function
      
      at Object.<anonymous> (node_modules/gdal/lib/gdal.js:58:14)
      at Object.<anonymous> (src/server/gis/raster/index.js:3:39)
      at Object.<anonymous> (src/server/gis/raster/index.test.js:3:14)
          at <anonymous>
```

But everything works fine if I run only one test file (whichever it may be).

**Comment by AlokBansal8** [comment]
For your reference line 3 of `index.js` is 

```js
import gdal from 'gdal'
```

**Comment by AlokBansal8** [comment]
@brandonreavis @brianreavis Please help. I am not able to write a comprehensive test suite for my project.

**Comment by brandonreavis** [comment]
I am not very familiar with Jest, but it looks like jest is loading and running the same module twice in the same process, which is not what node is supposed to do. `import` should load the module once, and add it to the cache.

If loaded twice, these lines cause `gdal.config.set` to be undefined:

https://github.com/naturalatlas/node-gdal/blob/master/lib/gdal.js#L52-L55

I'd recommend asking someone who understands jest if there is a way to have dependencies only loaded once.

**Comment by eduardogspereira** [comment]
Hi @AlokBansal8,

I had the same problem here. To solve it I inserted the GDAL_DATA variable on the tests.

```bash
"test": "GDAL_DATA=node_modules/gdal/deps/libgdal/gdal/data jest int --coverage --watch"
```

:+1::biking_man::biking_man:
