### ISSUE TITLE
Excute 'npm install gdal --save' error.

### ISSUE THREAD

**Issue by KunerRick** [naturalatlas/node-gdal#215]
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/gdal/v0.9.6/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for gdal@0.9.6 and node@7.2.0 (node-v51 ABI) (falling back to source compile with node-gyp)

**Comment by jdesboeufs** [comment]
Hi,

Node 7 is a deprecated version for which `node-gdal` binaries are no longer provided.
You should switch to Node 8 (or Node 6) or try some previous `node-gdal` versions.

**Comment by jdesboeufs** [comment]
Particularly `node-gdal@0.9.4`

**Comment by KunerRick** [comment]
ok, I'll try it.
