### ISSUE TITLE
How to create Geometry for SetSpatialFilter

### ISSUE THREAD

**Issue by O-mkar** [naturalatlas/node-gdal#217]
This is how my python code  looks like i was trying to convert it to nodejs using node gdal 
```
   [lon,lat,z]=ctran.TransformPoint(73.880428, 15.475545)

    #Create a point
    pt = ogr.Geometry(ogr.wkbPoint)
    pt.SetPoint_2D(0, lon, lat)

    layer.SetSpatialFilter(pt)
```

Here is my node code looks like.

```
   var pt = ctran.transformPoint(73.880428, 15.475545);

  var pt2 = gdal.Geometry.fromWKB(pt)  <<<---- THIS DOESNT WORK

  layer.setSpatialFilter(pt2); 
```

**Comment by brandonreavis** [comment]
`CoordinateTransformation.transformPoint()` returns a normal object with x and y properties [(described here)](http://naturalatlas.github.io/node-gdal/classes/gdal.CoordinateTransformation.html#method-transformPoint)

So all you need to do is
```
 var pt = ctran.transformPoint(73.880428, 15.475545);
 var pt2 = new gdal.Point(pt.x, pt.y);
 layer.setSpatialFilter(pt2); 
```
