### ISSUE TITLE
Unable to use in Electron

### ISSUE THREAD

**Issue by benjaminsaljooghi** [naturalatlas/node-gdal#219]
EDIT: Solved! See my comment below.

---

**OS:** Windows 10
**Node:** v8.9.1

To reproduce:

```
git clone https://github.com/electron/electron-quick-start.git
cd .\electron-quick-start\
npm install gdal --save
npm install --save-dev electron-rebuild
npm install
.\node_modules\.bin\electron-rebuild.cmd
```

Add the following to the script section in `index.html`:

```JavaScript
var gdal = require('gdal');
```

Finally:

```
npm start
```

`Ctrl + Shift + I` shows:

![image](https://user-images.githubusercontent.com/15173618/34405693-66048800-ec00-11e7-8446-6f01915d16a2.png)

I created this process by examining #127, #176, and [Using Native Node Modules](https://electronjs.org/docs/tutorial/using-native-node-modules).

Awesome module by the way. I just wish I could use it in Electron.

**Comment by benjaminsaljooghi** [comment]
Solved! As per the suggestion in #215, instead of

```
npm install gdal --save
```

Using

```
npm install gdal@0.9.4 --save
```

Allows me to use the binaries which were provided in this version and to therefore build the module for Electron.

I don't know why I didn't think of this, but thanks @jdesboeufs!

I'll leave the issue open though because the current version is not usable with Electron. Will this be fixed in #214?

**Comment by benjaminsaljooghi** [comment]
Issue closed by #214. You can now use this module in Electron by following my process in the first comment.

**Comment by xiaojuncumt** [comment]
0.9.4 version always installed failed,and this issue is solved in 2017.
it's 2019 now, i try the newest version still can't be used in electron,
is there a plan that the newest version can be used with electron?

**Comment by danielbarela** [comment]
I am able to use the newest version in electron.  You may want to look at this: https://github.com/electron-userland/electron-builder/issues/4253
