### ISSUE TITLE
can't load M value of shapefile

### ISSUE THREAD

**Issue by zhangjinzhou** [naturalatlas/node-gdal#228]
I opened a linestring shapefile with 0.9.6 version. It reads X,Y value correctly but not the M dimension. M value of all points is 0.
The only function I can use is Feature.getGeometry. I didn't find anything like getGeometryZM. Should we add this feature to current version?

**Comment by brandonreavis** [comment]
Unfortunately we haven't gotten around to exposing M values yet, but it should be simple to add.
https://github.com/naturalatlas/node-gdal/blob/master/src/gdal_point.cpp#L207

In the meantime, if you need to a workaround you can do something like this (assuming the geometry is a point): 
```js
function getM(pt) {
	var wkb = pt.toWKB();
	return wkb.readInt8(0) ? wkb.readDoubleBE(29) : wkb.readDoubleLE(29);
}
```

**Comment by zhangjinzhou** [comment]
Thanks @brandonreavis ! This method works perfectly.
