### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Derrekito** [naturalatlas/node-gdal#236]
## Update III

I rolled back to 8.11.2 and install was successful. I assume the repo needs to be upgraded to work for v9.x and greater.

### Installation on Windows platform.

I receive identical behavior When I attempted to install gdal on Windows 10 x64

### Installation using node 0.9.6 on GNU/Linux x64

Same failure messages.

## Update I

Running `make` after mirroring the repository did not solve the issue. I had hoped that compiling it myself would allow me to move forward since the previous errors reported no binaries for my platform were hosted @ makebox CDN provider (i.e., Amazon). However, there seems to be improper parameters sent to the nodejs builder. The error appears to stem from `src/fast_buffer.cpp`. Please see the terminal output below.

> ```
> ../src/utils/fast_buffer.cpp:18:80: error: no matching function for call to 'v                                                                                                                 8::Function::NewInstance(int, v8::Local<v8::Value> [3])' `                                                                                                                                      
> al<Object> actualBuffer = bufferConstructor->NewInstance(3, constructorArgs);
> ```

and soon after 

> ```
> /.node-gyp/10.4.0/include/node/v8.h:3905:44: note:   candidate expects 3 arguments, 2 provided
> make[1]: *** [gdal.target.mk:157: Release/obj.target/gdal/src/utils/fast_buffer.o] Error 1
> ```

original post below 
---
I receive the same error during install attempt against tarball https://github.com/naturalatlas/node-gdal/archive/v0.9.6.tar.gz or by following the README.md instructions. I have compiled and installed the full GDAL 2.3.0 installed for GNU/Linux x86_64 architecture.

Relying on npm using `npm i geotiff2json` yields a failed attempt to install v.0.7.2

Inserting `npm install gdal --build-from-source --shared_gdal` into the terminal yields a failed attempt to install 0.9.6

Output:

> ```
> node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/gdal/v0.9.6/node-v64-linux-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for gdal@0.9.6 and node@10.4.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
> node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/gdal/v0.9.6/node-v64-linux-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for gdal@0.9.6 and node@10.4.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
> ```

**Is this simply a compatibility issue with node 10.4.0?**

**Comment by spydmobile** [comment]
Bump, this is valid issue, is anything being done to address it?

**Comment by brianreavis** [comment]
https://github.com/naturalatlas/node-gdal/releases/tag/v0.10.0
