### ISSUE TITLE
Query tool - eg: gdallocationinfo 

### ISSUE THREAD

**Issue by spydmobile** [naturalatlas/node-gdal#248]
Hi, for the life of me, I cannot figure out how to query the value of a pixel at a given location using this module. Am I missing something obvious or is this just not possible?
thanks!

**Comment by brandonreavis** [comment]
I think this is what you are looking for:
https://github.com/naturalatlas/node-gdal/issues/192#issuecomment-286394999

**Comment by spydmobile** [comment]
Ye sir it was, thank you Brandon!!! Silly me I forgot to search the closed issues!
