### ISSUE TITLE
band ReadRaster and WriteRaster not found

### ISSUE THREAD

**Issue by FreeGIS** [naturalatlas/node-gdal#261]
i read the gdal api for java had some api can read and write raster band:
in_band1.ReadRaster(offset_x, offset_y, block_xsize, block_ysize, image_Xbuf, image_Ybuf,gdalconst.GDT_Int32, band1BuffData, 0, 0);
in_band2.ReadRaster(offset_x, offset_y, block_xsize, block_ysize, image_Xbuf, image_Ybuf,gdalconst.GDT_Int32, band2BuffData, 0, 0);
in_band3.ReadRaster(offset_x, offset_y, block_xsize, block_ysize, image_Xbuf, image_Ybuf,gdalconst.GDT_Int32, band3BuffData, 0, 0);
 In node-gdal i can not found write band api

**Comment by brandonreavis** [comment]
They are exposed via `band.pixels.read()` and `band.pixels.write()` 

Documentation:
http://naturalatlas.github.io/node-gdal/classes/gdal.RasterBandPixels.html

The tests contain examples of usage here:
https://github.com/naturalatlas/node-gdal/blob/master/test/api_rasterband.test.js#L479
