### ISSUE TITLE
gdal.Envelope intersect error

### ISSUE THREAD

**Issue by FreeGIS** [naturalatlas/node-gdal#262]
in node gdal:
`
let bbox1=
{
  minX: 39.28650720617374,
  minY: -5.743046418788738,
  maxX: 39.31361982006289,
  maxY: -5.770217452303509
};
let bbox2=
{
  minX: 39.298095703125,
  minY: -5.779966445034034,
  maxX: 39.30908203125,
  maxY: -5.769035866122143
};
bbox2.intersect(bbox1);
console.log(bbox2);`
result:
`
{
  minX: 0,
  minY: 0,
  maxX: 0,
  maxY: 0,
};`

but i test in postgis:
` select st_astext(ST_intersection(ST_MakeEnvelope(39.298095703125,-5.779966445034034,39.30908203125,-5.769035866122143,4326),								ST_MakeEnvelope(39.28650720617374,-5.743046418788738,39.31361982006289,-5.770217452303509,4326)));`

result:
`POLYGON((39.298095703125 -5.77021745230351,39.298095703125 -5.76903586612214,39.30908203125 -5.76903586612214,39.30908203125 -5.77021745230351,39.298095703125 -5.77021745230351))`

so i think the funtion has some bug.

**Comment by brandonreavis** [comment]
In your `bbox1`, `minY` is greater than `maxY`. If you fix that, it will work. That said, we should validate the input parameters better.
