### ISSUE TITLE
node-pre-gyp

### ISSUE THREAD

**Issue by dimitrisal** [naturalatlas/node-gdal#265]
I get the following message and the installation doesn't move forward. 

Any idea why this is happening?
node v10.15.3 npm 6.9.0
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/gdal/v0.9.9/node-v64-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for gdal@0.9.9 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by TonAbs** [comment]
I was getting these issues and I did the following and I solved it by downgrading Node to a supported version and installing windows build_tools 2015

**Comment by brianreavis** [comment]
Fixed by https://github.com/naturalatlas/node-gdal/releases/tag/v0.10.0
