### ISSUE TITLE
error installing on windows

### ISSUE THREAD

**Issue by ababakanian** [naturalatlas/node-gdal#274]
using nodejs v12.13.1
peforming a simple install using: npm install gdal --save

gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\ababakanian\\Desktop\\onsitemapserver\\map-db\\node_modules\\gdal\\lib\\binding\\node-v72-win32-x64\\gdal.node" "--module_name=gdal" "--module_path=C:\\Users\\ababakanian\\Desktop\\onsitemapserver\\map-db\\node_modules\\gdal\\lib\\binding\\node-v72-win32-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd C:\Users\ababakanian\Desktop\onsitemapserver\map-db\node_modules\gdal
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\ababakanian\Desktop\onsitemapserver\map-db\node_modules\gdal\lib\binding\node-v72-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\ababakanian\Desktop\onsitemapserver\map-db\node_modules\gdal\lib\binding\node-v72-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\ababakanian\Desktop\onsitemapserver\map-db\node_modules\gdal\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ababakanian\\Desktop\\onsitemapserver\\map-db\\node_modules\\gdal\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"   
node-pre-gyp ERR! cwd C:\Users\ababakanian\Desktop\onsitemapserver\map-db\node_modules\gdal
node-pre-gyp ERR! node -v v12.13.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\ababakanian\Desktop\onsitemapserver\map-db\node_modules\gdal\lib\binding\node-v72-win32-x64\gdal.node --module_name=gdal --module_path=C:\Users\ababakanian\Desktop\onsitemapserver\map-db\node_modules\gdal\lib\binding\node-v72-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gdal@0.9.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gdal@0.9.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ababakanian\AppData\Roaming\npm-cache\_logs\2020-07-28T01_31_01_712Z-debug.log

**Comment by frezzzms** [comment]
I also got similar error. NodeJS  v12.18.2 and NPM v6.14.8

**Comment by ShareQiu1994** [comment]
I also got similar error. NodeJS v12.16.3 and NPM v6.14.8

**Comment by brianreavis** [comment]
Fixed by https://github.com/naturalatlas/node-gdal/releases/tag/v0.10.0
