### ISSUE TITLE
gdal.Driver.create's parameter: data_type which need  Integer(number) , however , Constants (GDT) : gdal.GDT_* provide string

### ISSUE THREAD

**Issue by c101088** [naturalatlas/node-gdal#280]

**Comment by c101088** [comment]
I can find the cpp src file gdal.h reference in http://nagyak.eastron.hu/doc/gdal-1.6.2/docs/docs-64/gdal_8h.html ,  in which , "

enum | GDALDataType
-- | --
show the integer . Could it be useful?

**Comment by brandonreavis** [comment]
On the javascript side the string form of each constant is used, but the binding automatically translates the strings back to integers before calling the native gdal method. 

See https://github.com/naturalatlas/node-gdal/blob/master/src/gdal_driver.cpp#L272 for reference.

**Comment by c101088** [comment]
here is my code : 

> ```const tempDataSet:gdal.Dataset = gdal.drivers.get("GTiff").create("temp//"+destFileName+".tif", width,height,this.band,gdal.GDT_Float32);```
