### ISSUE TITLE
Node.js 14

### ISSUE THREAD

**Issue by zhangjinzhou** [naturalatlas/node-gdal#284]
Hi I used to have node.js 10 and it works fine. After upgrading to nodejs 14, I am not able to use the old package or install it. Is it supposed to work with nodejs 14 on Ubuntu?

**Comment by weagle08** [comment]
Use this one if you are upgrading to nodeJS v14... it's a fork

[https://github.com/contra/node-gdal-next](node-gdal-next)

**Comment by brianreavis** [comment]
What version of node-gdal are you using? As of [v0.10.0](https://github.com/naturalatlas/node-gdal/releases/tag/v0.10.0) we support up to Node 14.

**Comment by zhangjinzhou** [comment]
> Use this one if you are upgrading to nodeJS v14... it's a fork
> 
> [https://github.com/contra/node-gdal-next](node-gdal-next)

Thanks @weagle08 this solved my problem
