### ISSUE TITLE
Multi process Read Error

### ISSUE THREAD

**Issue by MuhammedKalkan** [naturalatlas/node-gdal#289]
Hello,

I have combined a tiff about 208 GB of size. 24 Processes are reading only and processing this data. Randomly i get this error below.
I havent seen this ever before. I thought maybe file is corrupted, and reproduced tiff. Still the same. 

At first i thought it was deterministic and same pixels give the error, but it doesnt.

One more thing is , error is always on X column. Here is another one

`IReadBlock failed at X offset 0, Y offset 242021: TIFFReadEncodedStrip() failed.`

Version is 0.11.1. Any ideas about how this can be resolved ? 

`(node:2252) UnhandledPromiseRejectionWarning: Error: G:/combined.tif, band 1: IReadBlock failed at X offset 0, Y offset 597129: TIFFReadEncodedStrip() failed.
    at RasterBandPixels.read (...\node_modules\gdal\lib\gdal.js:672:15)
  ...
(Use node --trace-warnings ... to show where the warning was created)`

**Comment by brandonreavis** [comment]
I am closing this because this is more of gdal issue rather than a node-gdal issue, but perhaps this is relevant and helpful:
https://gis.stackexchange.com/questions/252282/gdal-wont-read-geotiff-in-parallel-but-will-read-it-in-serial-and-will-read-v
