### ISSUE TITLE
Transform function erroring with no error.message

### ISSUE THREAD

**Issue by GretaCB** [naturalatlas/node-gdal#82]
Ran a few TIFF files through `mapnik-omnivore`, which is using node-gdal to call the CoordinateTransform function [here](https://github.com/mapbox/mapnik-omnivore/blob/master/lib/datasource-processor.js#L360).

Error output is simply `[Error]`

Not sure if error logging is already setup for the C++ Transform function, or maybe this is a new testcase that isn't included in the error logic yet.

Let me know if you want to take a look at any of the failing files.

cc @springmeyer @camilla

**Comment by springmeyer** [comment]
@GretaCB can you try to reduce the testcase to a small js file? From the spot in the code you linked it looks like you might be able to console.log out the  `center` object and then see if you can replicate the error with a standalone script that just does something like:

```
var gdal = require('gdal')

var halfPixelsPerUnit = <something>;
var center = <something>;
var line = new gdal.LineString();
line.points.add(center[0], (center[1] - halfPixelsPerUnit));
line.points.add(center[0], (center[1] + halfPixelsPerUnit));
line.transform(transform);
 ```

**Comment by brandonreavis** [comment]
`Geometry.transform` is implemented and reports errors like all of the other methods, but GDAL doesn't always report error information. Unfortunately it looks like you ran into one of those cases. Yeah, if you could post the WKT of the source and target spatial references, as well as the WKT of the geometry that would help a lot!

**Comment by GretaCB** [comment]
@springmeyer here is that test case with the file's center/halfpixelperunit values...
```
var gdal = require('gdal')

var halfPixelsPerUnit = 0.2499847095;
var center = 660136.1000001298,5101022.320000152;
var line = new gdal.LineString();
line.points.add(center[0], (center[1] - halfPixelsPerUnit));
line.points.add(center[0], (center[1] + halfPixelsPerUnit));
line.transform(transform);
```

@brandonreavis ran `gdalinfo` on the file...
```
Driver: GTiff/GeoTIFF
Files: camilla.tif
Size is 6540, 6860
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (658501.199999999837019,5102737.290000000037253)
Pixel Size = (0.499969419000000,-0.499991253600000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  658501.200, 5102737.290) (Invalid angle,Invalid angle)
Lower Left  (  658501.200, 5099307.350) (Invalid angle,Invalid angle)
Upper Right (  661771.000, 5102737.290) (Invalid angle,Invalid angle)
Lower Right (  661771.000, 5099307.350) (Invalid angle,Invalid angle)
Center      (  660136.100, 5101022.320) (Invalid angle,Invalid angle)
Band 1 Block=6540x1 Type=Byte, ColorInterp=Red
Band 2 Block=6540x1 Type=Byte, ColorInterp=Green
Band 3 Block=6540x1 Type=Byte, ColorInterp=Blue
```

**Comment by brandonreavis** [comment]
The file uses WGS84 and the corner coordinates are like (658501.200, 5102737.290)? It looks like the geotransform of the file was set to something invalid...that or the projection of the file is set wrong.

**Comment by GretaCB** [comment]
Thanks @brandonreavis 

@camillacaros , were these reprojected?

**Comment by camillacaros** [comment]
hey, sorry for my delay here, lost track of this

@GretaCB they were reprojected, but it looks like something went wrong with my process there.  I just successfully uploaded a different TIF file (also reprojected, but properly) & it shows up in my /data page immediately.

Thanks for the help tracking this down.  My confusion mostly came from my mapbox.com/data page giving an "Upload complete" message & then having no data actually show up. @GretaCB you mentioned error message cases like this are already being addressed somewhere.  I'm curious to see that conversation, if you know where to point me.

**Comment by springmeyer** [comment]
Thanks all, will close this up then as it turns out to not be a node-gdal issue.
