### ISSUE TITLE
0.4.2 release

### ISSUE THREAD

**Issue by springmeyer** [naturalatlas/node-gdal#90]
Thinking its a good time for a minor release to hit:

  - [x] Nan upgrade -> unlocks io.js/node v0.12.x support
  - [x] GDAL 1.11.2 upgrade (will also release node-mapnik and node-srs that use same exact GDAL version to prevent runtime crashes due to ABI incompatibility)
  - [ ] Drop node v0.11.x testing and pre-built binaries (no need for these now what node v0.12 is out)

Anyone have other needs or thoughts?

@brandonreavis @brandonreavis @GretaCB @BergWerkGIS @rclark

**Comment by brianreavis** [comment]
@springmeyer Sounds awesome to me. @brandonreavis and I have talked about getting the OSM driver in too – should be a quick addition.

Also, if there's no downside besides build time, I'd like to keep v0.11.x binaries around for the folks who haven't migrated to 0.12 yet. Is that cool?

**Comment by springmeyer** [comment]
> I'd like to keep v0.11.x binaries around for the folks who haven't migrated to 0.12 yet. Is that cool?

That is fine if you'd like. I just figured nobody was using them since I removed v0.11.x support in node-sqlite3 (https://github.com/mapbox/node-sqlite3/blob/master/.travis.yml#L16-L22) and have not heard any complaints.

**Comment by springmeyer** [comment]
@brianreavis - I see you started on this ^^ Thanks! Let me know if you need anything from me to get a release out.

**Comment by brianreavis** [comment]
@springmeyer Looks like @brandonreavis and I aren't the only ones on the graveyard shift! I think we're good for the release. I just need to enable 0.12 on Appveyor and push it out – let's give it a shot tonight

**Comment by springmeyer** [comment]
Hey fellow graveyarders :)

![](http://media.giphy.com/media/6QJaosMyvdhHa/giphy.gif)

Release tomorrow or monday would be fantastic! I'll followup after the tag/publish to build the custom visual studio 2014 binaries I pull in for Studio (I do this by booting a VM for now but def want to automate in the future). Thanks!

**Comment by brianreavis** [comment]
Success! 
https://ci.appveyor.com/project/brianreavis/node-gdal/build/476
https://travis-ci.org/naturalatlas/node-gdal

**Comment by springmeyer** [comment]
\o/ just pushed the vs 2014 builds too.

**Comment by brianreavis** [comment]
@springmeyer Epic! I think this has been the smoothest release yet
