### ISSUE TITLE
Bad overviews missing data

### ISSUE THREAD

**Issue by rclark** [naturalatlas/node-gdal#93]
I noticed that there seemed to be some data dropped when creating overviews of tif files. My hunch is that it may have to do with the tif's internal block size? The files I've been dealing with are TILED=YES. 

Here's what I did to recreate the problem:

```js
var gdal = require('gdal');
var outfile = './original.tif';
var ds = gdal.open(outfile, 'r+');
ds.buildOverviews('CUBIC', [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]);
```

After running that javascript, I used `tiffsplit` to cut the overviews out of the tif.
```
tiffsplit original.tif original-
```

Inspecting some of the overviews, it looks like individual blocks are missing the 3rd band, resulting in yellow pixels:

![presorcery-aaf](https://cloud.githubusercontent.com/assets/515424/6721428/3e741630-cd8a-11e4-8dbd-1165fbbc0c7d.png)

To compare, I tried the same procedure with `gdaladdo` + `tiffsplit` and did not see the yellow block.

```
gdaladdo -r cubic original.tif 2 4 8 16 32 64 128 256 512 1024
```

Some fixtures:
- [original file without overviews](https://s3.amazonaws.com/mapbox/playground/rclark/overviews/original.tif)
- [file with node-gdal-built overviews](https://s3.amazonaws.com/mapbox/playground/rclark/overviews/with-overviews.tif)
- [example overview with yellow block](https://s3.amazonaws.com/mapbox/playground/rclark/overviews/overview-example.tif)

**Comment by brandonreavis** [comment]
Hey Ryan!

Sorry for taking a while to get to this. I was able to reproduce your issue too. 

Making sure the dataset is closed and flushed before the process exits fixes the problem for me. Datasets get closed automatically when node garbage collects them, but there is no guarantee that node will garbage collect before exiting.

```js
var gdal = require('gdal');
var outfile = './original.tif';
var ds = gdal.open(outfile, 'r+');
ds.buildOverviews('CUBIC', [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]);
ds.close();
```

**Comment by rclark** [comment]
Excellent news -- that's an easy fix. Thanks for taking a look!
