### ISSUE TITLE
Discrepancy with node-gdal srs (Results in empty object)

### ISSUE THREAD

**Issue by BerryDaniel** [naturalatlas/node-gdal#95]
I have tested this with multiple rasters and shapefiles, below is the output of using one of your test files 'multiband.tif'. gdalinfo via command line displays the srs as EPSG:3857, but the node-gdal displays it as an empty object. I have attempted to set the PROJ_LIB in the main app.js...
process.env['PROJ_LIB'] = './data/proj';

It just doesn't appear to be able to access the projection library. I am using the npm install gdal and I have tried this on OSX and WIN7, but result in the following:

var ds = gdal.open(obj.path); //obj.path contains path to multiband.tif
console.log(JSON.stringify(ds,null,2));

{
  "geoTransform": [
    -11584184.5107,
    30.00058143924877,
    0,
    5635549.221409999,
    0,
    -30.00058143924877
  ],
  "srs": {},
  "driver": {
    "description": "GTiff"
  },
  "rasterSize": {
    "x": 512,
    "y": 512
  },
  "layers": {},
  "bands": {},
  "description": "watch_dir/inbound/multiband.tif"
}

any ideas?

**Comment by brianreavis** [comment]
I wouldn't use `JSON.stringify` on any of the node-gdal objects – the output is bound to be strange (we don't define `toJSON` and the object itself is native). What's the output of `ds.srs.toPrettyWKT()` ([docs](http://naturalatlas.github.io/node-gdal/classes/gdal.SpatialReference.html#method-toPrettyWKT))?

**Comment by BerryDaniel** [comment]
I see, thank you for the clarification. The output of ds.srs.toPrettyWKT()
is correct.

Daniel Berry
512.468.3946 - Cell number
217.434.4101 - Skype number
