### ISSUE TITLE
Odd geometryType value for wkbPoint25D

### ISSUE THREAD

**Issue by GretaCB** [naturalatlas/node-gdal#96]
Came across a shapefile that has a `layer.geomType` of `2147483649`, which is triggering the following error when attempting [to create a mirrored datasource layer](https://github.com/mapbox/node-wmshp/blob/master/index.js#L23)...

`[TypeError: geometry type must be an integer]`

Is this integer value valid? Or is there a possible bug?

I used `ogr2ogr` to create a copy of the file to see if OGR would fail or if the new shapefile would have a different geomType value, but it was the same. Thinking this might be targeted to node-gdal.

cc @brianreavis @brandonreavis

**Comment by brandonreavis** [comment]
Hmm... that number is bigger than a signed 32-bit integer. Is it a 2.5D point shapefile? I'm thinking node-gdal might have some problems dealing with signed vs. unsigned numbers. That should be easily fixed once I confirm this is the problem.

Can you post the shapefile? I don't have access to the unpacker repository. Thanks!

**Comment by GretaCB** [comment]
ogrinfo reports the Geometry as `3D Point`. File is [here](https://www.dropbox.com/s/h54awnol42d80jc/jeffpickles.zip?dl=0)

**Comment by brandonreavis** [comment]
Yeah, it does seem that it was an issue of node-gdal only allowing signed integers for enum values, when it should have accepted unsigned integers all along. It should be fixed and ready to go once the tests pass!

**Comment by GretaCB** [comment]
Thanks so much @brandonreavis !

**Comment by GretaCB** [comment]
@brandonreavis do we need to update gdal version on our side for this fix?

**Comment by brandonreavis** [comment]
No problem! Yeah you'll need to use 0.4.3 now, which is ready for linux/mac, but it might take the next few hours building on windows.

**Comment by BergWerkGIS** [comment]
I just published the Windows binaries for Visual Studio 2014 CTP4 (AppVeyor is too slow to build them in time).
These are necessary e.g. for [mapnik-omnivore](https://github.com/mapbox/mapnik-omnivore/blob/master/appveyor.yml#L6-L11).
