### ISSUE TITLE
SIGSEGV when opening .jp2

### ISSUE THREAD

**Issue by knutole** [naturalatlas/node-gdal#97]
(Not the right place to post this, perhaps, but desperate times and so on.)

Have compiled GDAL with ECW/JP2 support, and while eg. `gdalinfo sample.ecw` works well, `gdalinfo sample.jp2` throws `terminated by signal SIGSEGV (Address boundary error)`. (52MB .jp2 file.)

Just wondering if anyone has any experience with this. The `node-gdal` bindings throw the same error, obviously. Any input or debug hints much appreciated.

Compiled like thus:
```

# Get libecwj2-3.3 (ECW + JPEG2000 dependency)
cd /var/www/deps/
wget http://de-mirror.org/gentoo/distfiles/libecwj2-3.3-2006-09-06.zip
unzip libecwj2-3.3-2006-09-06.zip

# get patches and patch! http://wiki.openstreetmap.org/wiki/ECW#Building_libecwj
wget http://trac.osgeo.org/gdal/raw-attachment/ticket/3162/libecwj2-3.3-msvc90-fixes.patch
patch -p0 < libecwj2-3.3-msvc90-fixes.patch
wget http://osgeo-org.1560.x6.nabble.com/attachment/5001530/0/libecwj2-3.3-wcharfix.patch
wget http://trac.osgeo.org/gdal/raw-attachment/ticket/3366/libecwj2-3.3-NCSPhysicalMemorySize-Linux.patch
cd libecwj2-3.3/
patch -p0 < ../libecwj2-3.3-NCSPhysicalMemorySize-Linux.patch
patch -p1 < ../libecwj2-3.3-wcharfix.patch

# configure && make
./configure
make
make install

# Compile GDAL with ECW + JPEG2000 support
./configure --with-png=internal --with-jpeg=internal --with-geotiff=internal --with-libtiff=internal --with-ecw=/usr/local
make
sudo make install

```

**Comment by brianreavis** [comment]
I can't say I'm familiar with this problem – I'm not sure what it could be without really digging into it. This question is probably better suited for [GIS StackExchange](http://gis.stackexchange.com/) or the [GDAL bug tracker](https://trac.osgeo.org/gdal/newticket).
