### ISSUE TITLE
Geometry.toWKB() variant parameter is broken.

### ISSUE THREAD

**Issue by brandonreavis** [naturalatlas/node-gdal#98]
This section has a typo, and the error message is incorrect:

https://github.com/naturalatlas/node-gdal/blob/master/src/gdal_geometry.cpp#L629-L636

**Comment by OferE** [comment]
+1.
I'm trying to read a buffer taken from postgis into geometry using the following code:
...
 client.query('SELECT ST_AsEWKB(geom) as geom FROM tiles WHERE id = $1', ['1'], function(err, result) {
   ...
      var res = result.rows[0].geom;
      var res1 = gdal.Geometry.fromWKB(res);


and i am getting the following error on res:
Error: Argument must be a buffer object


I checked and res is a Buffer...

Thanks,
Ofer
